dependencies {
    implementation project(':application')
    implementation project(':security-module')
    implementation project(':api-common-module')

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    runtimeOnly project(':infrastructure:persistence')
    runtimeOnly project(':infrastructure:redis')
    runtimeOnly project(':infrastructure:file-storage')
    runtimeOnly project(':infrastructure:oauth')
    runtimeOnly project(':infrastructure:payment')
    runtimeOnly project(':infrastructure:messaging')
    runtimeOnly project(':logging-module')

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.2.1'
    testImplementation(testFixtures(project(':application')))
}
