dependencies {
    implementation project(':application')
    implementation project(':infrastructure:persistence')
    implementation project(':external-api')
    implementation project(':logging-module')
    implementation project(':security-module')
    implementation project(':infrastructure:redis')
    implementation project(':api-common-module')

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.2.1'
    testImplementation(testFixtures(project(':application')))
}
