plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.security:spring-security-core'

    api 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.12.1'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
