rootProject.name = 'tastyhouse-api'

include 'web-api'
include 'admin-api'
include 'ceo-api'
include 'domain-module'
include 'infrastructure-module'
include 'external-api'
include 'logging-module'
include 'batch-module'
include 'batch-application'
include 'web-application'
include 'admin-application'
include 'ceo-application'
include 'security-module'
include 'api-common-module'
include 'application-common-module'
