rootProject.name = 'tastyhouse-api'

include 'web-api'
include 'admin-api'
include 'ceo-api'
include 'domain-module'
include 'infrastructure:persistence'
include 'infrastructure:redis'
include 'infrastructure:external'
include 'logging-module'
include 'batch-module'
include 'application'
include 'security-module'
include 'security-core'
include 'api-common-module'
