rootProject.name = 'tastyhouse-api'

include 'web-api'
include 'admin-api'
include 'ceo-api'
include 'domain-module'
include 'infrastructure:persistence'
include 'infrastructure:redis'
include 'infrastructure:external'
include 'infrastructure:firebase'
include 'infrastructure:file-storage'
include 'infrastructure:aws'
include 'infrastructure:oauth'
include 'infrastructure:payment'
include 'infrastructure:messaging'
include 'infrastructure:crawling'
include 'logging-module'
include 'batch-module'
include 'application'
include 'security-module'
include 'security-core'
include 'api-common-module'
