plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    implementation project(':infrastructure:external')
    implementation project(':domain-module')

    implementation 'com.google.firebase:firebase-admin:9.10.0'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
