package com.tastyhouse.infrastructure.payment.persistence;

import com.tastyhouse.domain.payment.model.TossPaymentRecord;
import com.tastyhouse.domain.payment.vo.PaymentId;
import com.tastyhouse.infrastructure.shared.persistence.IdMapping;

final class TossPaymentRecordMapper {
    private TossPaymentRecordMapper() {
    }

    static TossPaymentRecord toDomain(TossPaymentRecordJpaEntity entity) {
        return TossPaymentRecord.reconstitute(
            entity.getId(),
            IdMapping.vo(entity.getPaymentId(), PaymentId::of),
            entity.getVersion(),
            entity.getPaymentKey(),
            entity.getType(),
            entity.getOrderId(),
            entity.getOrderName(),
            entity.getMId(),
            entity.getCurrency(),
            entity.getMethod(),
            entity.getTotalAmount(),
            entity.getBalanceAmount(),
            entity.getStatus(),
            entity.getRequestedAt(),
            entity.getApprovedAt(),
            entity.isUseEscrow(),
            entity.getLastTransactionKey(),
            entity.getSuppliedAmount(),
            entity.getVat(),
            entity.isCultureExpense(),
            entity.getTaxFreeAmount(),
            entity.getTaxExemptionAmount(),
            entity.isPartialCancelable(),
            entity.getCardAmount(),
            entity.getCardIssuerCode(),
            entity.getCardAcquirerCode(),
            entity.getCardNumber(),
            entity.getCardInstallmentPlanMonths(),
            entity.getCardApproveNo(),
            entity.isCardUseCardPoint(),
            entity.getCardType(),
            entity.getCardOwnerType(),
            entity.getCardAcquireStatus(),
            entity.isCardInterestFree(),
            entity.getCardInterestPayer(),
            entity.getVirtualAccountType(),
            entity.getVirtualAccountNumber(),
            entity.getVirtualAccountBankCode(),
            entity.getVirtualAccountCustomerName(),
            entity.getVirtualAccountDueDate(),
            entity.getVirtualAccountRefundStatus(),
            entity.isVirtualAccountExpired(),
            entity.getVirtualAccountSettlementStatus(),
            entity.getMobilePhoneCustomerMobilePhone(),
            entity.getMobilePhoneSettlementStatus(),
            entity.getMobilePhoneReceiptUrl(),
            entity.getTransferBankCode(),
            entity.getTransferSettlementStatus(),
            entity.getEasyPayProvider(),
            entity.getEasyPayAmount(),
            entity.getEasyPayDiscountAmount(),
            entity.getReceiptUrl(),
            entity.getCheckoutUrl(),
            entity.getFailureCode(),
            entity.getFailureMessage(),
            entity.getCountry(),
            entity.getCreatedAt()
        );
    }

    static TossPaymentRecordJpaEntity toEntity(TossPaymentRecord domain) {
        return TossPaymentRecordJpaEntity.create(
            IdMapping.raw(domain.getPaymentId(), PaymentId::value),
            domain.getVersion(),
            domain.getPaymentKey(),
            domain.getType(),
            domain.getOrderId(),
            domain.getOrderName(),
            domain.getMId(),
            domain.getCurrency(),
            domain.getMethod(),
            domain.getTotalAmount(),
            domain.getBalanceAmount(),
            domain.getStatus(),
            domain.getRequestedAt(),
            domain.getApprovedAt(),
            domain.isUseEscrow(),
            domain.getLastTransactionKey(),
            domain.getSuppliedAmount(),
            domain.getVat(),
            domain.isCultureExpense(),
            domain.getTaxFreeAmount(),
            domain.getTaxExemptionAmount(),
            domain.isPartialCancelable(),
            domain.getCardAmount(),
            domain.getCardIssuerCode(),
            domain.getCardAcquirerCode(),
            domain.getCardNumber(),
            domain.getCardInstallmentPlanMonths(),
            domain.getCardApproveNo(),
            domain.isCardUseCardPoint(),
            domain.getCardType(),
            domain.getCardOwnerType(),
            domain.getCardAcquireStatus(),
            domain.isCardInterestFree(),
            domain.getCardInterestPayer(),
            domain.getVirtualAccountType(),
            domain.getVirtualAccountNumber(),
            domain.getVirtualAccountBankCode(),
            domain.getVirtualAccountCustomerName(),
            domain.getVirtualAccountDueDate(),
            domain.getVirtualAccountRefundStatus(),
            domain.isVirtualAccountExpired(),
            domain.getVirtualAccountSettlementStatus(),
            domain.getMobilePhoneCustomerMobilePhone(),
            domain.getMobilePhoneSettlementStatus(),
            domain.getMobilePhoneReceiptUrl(),
            domain.getTransferBankCode(),
            domain.getTransferSettlementStatus(),
            domain.getEasyPayProvider(),
            domain.getEasyPayAmount(),
            domain.getEasyPayDiscountAmount(),
            domain.getReceiptUrl(),
            domain.getCheckoutUrl(),
            domain.getFailureCode(),
            domain.getFailureMessage(),
            domain.getCountry()
        );
    }
}
