package com.tastyhouse.infrastructure.payment.persistence;

import com.tastyhouse.domain.payment.model.TossPaymentRecord;
import com.tastyhouse.domain.payment.vo.PaymentId;

final class TossPaymentRecordMapper {
    private TossPaymentRecordMapper() {
    }

    static TossPaymentRecord toDomain(TossPaymentRecordJpaEntity entity) {
        return TossPaymentRecord.reconstitute(
            entity.getId(),
            entity.getPaymentId() == null ? null : PaymentId.of(entity.getPaymentId()),
            entity.getVersion(),
            entity.getPaymentKey(),
            entity.getType(),
            entity.getOrderId(),
            entity.getOrderName(),
            entity.getMId(),
            entity.getCurrency(),
            entity.getMethod(),
            entity.getTotalAmount(),
            entity.getBalanceAmount(),
            entity.getStatus(),
            entity.getRequestedAt(),
            entity.getApprovedAt(),
            entity.isUseEscrow(),
            entity.getLastTransactionKey(),
            entity.getSuppliedAmount(),
            entity.getVat(),
            entity.isCultureExpense(),
            entity.getTaxFreeAmount(),
            entity.getTaxExemptionAmount(),
            entity.isPartialCancelable(),
            entity.getCardAmount(),
            entity.getCardIssuerCode(),
            entity.getCardAcquirerCode(),
            entity.getCardNumber(),
            entity.getCardInstallmentPlanMonths(),
            entity.getCardApproveNo(),
            entity.isCardUseCardPoint(),
            entity.getCardType(),
            entity.getCardOwnerType(),
            entity.getCardAcquireStatus(),
            entity.isCardInterestFree(),
            entity.getCardInterestPayer(),
            entity.getVirtualAccountType(),
            entity.getVirtualAccountNumber(),
            entity.getVirtualAccountBankCode(),
            entity.getVirtualAccountCustomerName(),
            entity.getVirtualAccountDueDate(),
            entity.getVirtualAccountRefundStatus(),
            entity.isVirtualAccountExpired(),
            entity.getVirtualAccountSettlementStatus(),
            entity.getMobilePhoneCustomerMobilePhone(),
            entity.getMobilePhoneSettlementStatus(),
            entity.getMobilePhoneReceiptUrl(),
            entity.getTransferBankCode(),
            entity.getTransferSettlementStatus(),
            entity.getEasyPayProvider(),
            entity.getEasyPayAmount(),
            entity.getEasyPayDiscountAmount(),
            entity.getReceiptUrl(),
            entity.getCheckoutUrl(),
            entity.getFailureCode(),
            entity.getFailureMessage(),
            entity.getCountry(),
            entity.getCreatedAt()
        );
    }

    static TossPaymentRecordJpaEntity toEntity(TossPaymentRecord tossPaymentRecord) {
        return TossPaymentRecordJpaEntity.create(
            tossPaymentRecord.getPaymentId() == null ? null : tossPaymentRecord.getPaymentId().value(),
            tossPaymentRecord.getVersion(),
            tossPaymentRecord.getPaymentKey(),
            tossPaymentRecord.getType(),
            tossPaymentRecord.getOrderId(),
            tossPaymentRecord.getOrderName(),
            tossPaymentRecord.getMId(),
            tossPaymentRecord.getCurrency(),
            tossPaymentRecord.getMethod(),
            tossPaymentRecord.getTotalAmount(),
            tossPaymentRecord.getBalanceAmount(),
            tossPaymentRecord.getStatus(),
            tossPaymentRecord.getRequestedAt(),
            tossPaymentRecord.getApprovedAt(),
            tossPaymentRecord.isUseEscrow(),
            tossPaymentRecord.getLastTransactionKey(),
            tossPaymentRecord.getSuppliedAmount(),
            tossPaymentRecord.getVat(),
            tossPaymentRecord.isCultureExpense(),
            tossPaymentRecord.getTaxFreeAmount(),
            tossPaymentRecord.getTaxExemptionAmount(),
            tossPaymentRecord.isPartialCancelable(),
            tossPaymentRecord.getCardAmount(),
            tossPaymentRecord.getCardIssuerCode(),
            tossPaymentRecord.getCardAcquirerCode(),
            tossPaymentRecord.getCardNumber(),
            tossPaymentRecord.getCardInstallmentPlanMonths(),
            tossPaymentRecord.getCardApproveNo(),
            tossPaymentRecord.isCardUseCardPoint(),
            tossPaymentRecord.getCardType(),
            tossPaymentRecord.getCardOwnerType(),
            tossPaymentRecord.getCardAcquireStatus(),
            tossPaymentRecord.isCardInterestFree(),
            tossPaymentRecord.getCardInterestPayer(),
            tossPaymentRecord.getVirtualAccountType(),
            tossPaymentRecord.getVirtualAccountNumber(),
            tossPaymentRecord.getVirtualAccountBankCode(),
            tossPaymentRecord.getVirtualAccountCustomerName(),
            tossPaymentRecord.getVirtualAccountDueDate(),
            tossPaymentRecord.getVirtualAccountRefundStatus(),
            tossPaymentRecord.isVirtualAccountExpired(),
            tossPaymentRecord.getVirtualAccountSettlementStatus(),
            tossPaymentRecord.getMobilePhoneCustomerMobilePhone(),
            tossPaymentRecord.getMobilePhoneSettlementStatus(),
            tossPaymentRecord.getMobilePhoneReceiptUrl(),
            tossPaymentRecord.getTransferBankCode(),
            tossPaymentRecord.getTransferSettlementStatus(),
            tossPaymentRecord.getEasyPayProvider(),
            tossPaymentRecord.getEasyPayAmount(),
            tossPaymentRecord.getEasyPayDiscountAmount(),
            tossPaymentRecord.getReceiptUrl(),
            tossPaymentRecord.getCheckoutUrl(),
            tossPaymentRecord.getFailureCode(),
            tossPaymentRecord.getFailureMessage(),
            tossPaymentRecord.getCountry()
        );
    }
}
