package com.tastyhouse.application.shared.exception;

public enum ApplicationErrorCode implements ApplicationErrorCodeSpec {

    INVALID_INPUT(400, "INVALID_INPUT", "입력값이 올바르지 않습니다."),

    ORDER_NOT_FOUND(404, "ORDER_NOT_FOUND", "주문을 찾을 수 없습니다."),

    COUPON_NOT_FOUND(404, "COUPON_NOT_FOUND", "쿠폰을 찾을 수 없습니다."),
    COUPON_ACCESS_DENIED(403, "COUPON_ACCESS_DENIED", "본인의 쿠폰만 사용할 수 있습니다."),
    COUPON_INFO_NOT_FOUND(404, "COUPON_INFO_NOT_FOUND", "쿠폰 정보를 찾을 수 없습니다."),
    COUPON_ALREADY_ISSUED(409, "COUPON_ALREADY_ISSUED", "이미 발급된 쿠폰입니다."),

    PAYMENT_NOT_FOUND(404, "PAYMENT_NOT_FOUND", "결제를 찾을 수 없습니다."),
    PAYMENT_ORDER_ACCESS_DENIED(403, "PAYMENT_ORDER_ACCESS_DENIED", "본인의 주문만 결제할 수 있습니다."),
    PAYMENT_ACCESS_DENIED(403, "PAYMENT_ACCESS_DENIED", "본인의 결제만 처리할 수 있습니다."),
    PAYMENT_INVALID_ORDER_STATUS(400, "PAYMENT_INVALID_ORDER_STATUS", "결제할 수 없는 주문 상태입니다."),
    PAYMENT_ALREADY_IN_PROGRESS(400, "PAYMENT_ALREADY_IN_PROGRESS", "이미 결제가 진행 중인 주문입니다."),
    PAYMENT_NOT_PENDING_APPROVAL(400, "PAYMENT_NOT_PENDING_APPROVAL", "승인 대기 중인 결제만 처리할 수 있습니다."),
    PAYMENT_AMOUNT_MISMATCH(400, "PAYMENT_AMOUNT_MISMATCH", "결제 금액이 일치하지 않습니다."),
    PAYMENT_NOT_ON_SITE(400, "PAYMENT_NOT_ON_SITE", "현장결제만 완료 처리할 수 있습니다."),

    MEMBER_NOT_FOUND(404, "MEMBER_NOT_FOUND", "회원을 찾을 수 없습니다."),
    MEMBER_COUPON_NOT_FOUND(404, "MEMBER_COUPON_NOT_FOUND", "회원 쿠폰을 찾을 수 없습니다."),

    POINT_NOT_FOUND(404, "POINT_NOT_FOUND", "포인트 정보를 찾을 수 없습니다."),

    FILE_EMPTY(400, "FILE_EMPTY", "파일이 비어있습니다."),
    FILE_SIZE_EXCEEDED(400, "FILE_SIZE_EXCEEDED", "파일 크기는 10MB를 초과할 수 없습니다."),
    FILE_TYPE_NOT_ALLOWED(400, "FILE_TYPE_NOT_ALLOWED", "허용되지 않는 파일 형식입니다. (jpg, png, gif, webp만 가능)"),
    FILE_EXTENSION_NOT_ALLOWED(400, "FILE_EXTENSION_NOT_ALLOWED", "허용되지 않는 파일 확장자입니다. (jpg, png, gif, webp만 가능)"),
    FILE_EXTENSION_UNKNOWN(400, "FILE_EXTENSION_UNKNOWN", "파일 확장자를 확인할 수 없습니다."),
    FILE_STORE_FAILED(500, "FILE_STORE_FAILED", "파일 저장에 실패했습니다."),

    REVIEW_NOT_FOUND(404, "REVIEW_NOT_FOUND", "리뷰를 찾을 수 없습니다."),
    REVIEW_ACCESS_DENIED(403, "REVIEW_ACCESS_DENIED", "본인의 리뷰만 수정/삭제할 수 있습니다."),
    REVIEW_ALREADY_EXISTS(400, "REVIEW_ALREADY_EXISTS", "이미 리뷰를 작성한 상품입니다."),
    REVIEW_COMMENT_NOT_FOUND(404, "REVIEW_COMMENT_NOT_FOUND", "댓글을 찾을 수 없습니다."),
    NOTIFICATION_NOT_FOUND(404, "NOTIFICATION_NOT_FOUND", "알림을 찾을 수 없습니다."),
    REVIEW_BLIND_REQUEST_NOT_FOUND(404, "REVIEW_BLIND_REQUEST_NOT_FOUND", "게시중단 요청을 찾을 수 없습니다."),
    REVIEW_BLIND_REQUEST_ALREADY_PENDING(409, "REVIEW_BLIND_REQUEST_ALREADY_PENDING", "이미 게시중단 요청이 접수된 리뷰입니다."),
    REVIEW_BLIND_DETAIL_REASON_REQUIRED(400, "REVIEW_BLIND_DETAIL_REASON_REQUIRED", "기타 사유는 상세 내용을 입력해야 합니다."),
    REVIEW_BLIND_REQUEST_ALREADY_USED(409, "REVIEW_BLIND_REQUEST_ALREADY_USED", "이미 게시중단을 요청한 리뷰입니다. 동일한 리뷰는 1회만 요청할 수 있습니다."),

    SHOP_NOT_FOUND(404, "SHOP_NOT_FOUND", "존재하지 않는 가게입니다."),
    STATION_NOT_FOUND(404, "STATION_NOT_FOUND", "존재하지 않는 지하철역입니다."),
    SHOP_AMENITY_CATEGORY_NOT_FOUND(404, "SHOP_AMENITY_CATEGORY_NOT_FOUND", "존재하지 않는 편의시설 카테고리입니다."),
    SHOP_BUSINESS_HOUR_NOT_FOUND(404, "SHOP_BUSINESS_HOUR_NOT_FOUND", "존재하지 않는 운영시간입니다."),
    SHOP_BREAK_TIME_NOT_FOUND(404, "SHOP_BREAK_TIME_NOT_FOUND", "존재하지 않는 브레이크타임입니다."),

    SHOP_ACCESS_DENIED(403, "SHOP_ACCESS_DENIED", "해당 가게에 대한 접근 권한이 없습니다."),
    SHOP_BREAK_TIME_OUT_OF_BUSINESS_HOURS(400, "SHOP_BREAK_TIME_OUT_OF_BUSINESS_HOURS", "휴게시간은 영업시간 범위 안에서만 설정할 수 있습니다."),
    SHOP_BREAK_TIME_EQUALS_BUSINESS_HOURS(400, "SHOP_BREAK_TIME_EQUALS_BUSINESS_HOURS", "휴게시간을 영업시간과 완전히 동일하게 설정할 수 없습니다."),
    SHOP_REGULAR_CLOSED_DAY_LIMIT_EXCEEDED(400, "SHOP_REGULAR_CLOSED_DAY_LIMIT_EXCEEDED", "정기 휴무일은 최대 15개까지 설정할 수 있습니다."),
    SHOP_STATUS_CHANGE_BLOCKED_BY_PENDING_REQUEST(409, "SHOP_STATUS_CHANGE_BLOCKED_BY_PENDING_REQUEST", "진행 중인 승인 요청이 있어 가게 상태를 변경할 수 없습니다."),

    SHOP_TEXT_PROHIBITED_WORD(400, "SHOP_TEXT_PROHIBITED_WORD", "등록할 수 없는 문구가 포함되어 있습니다."),
    SHOP_INTRODUCTION_TOO_LONG(400, "SHOP_INTRODUCTION_TOO_LONG", "가게 소개는 최대 500자까지 입력할 수 있습니다."),
    SHOP_DISPLAY_LOCATION_OUT_OF_RANGE(400, "SHOP_DISPLAY_LOCATION_OUT_OF_RANGE", "노출 위치는 실제 위치 반경 1km 이내에서만 변경할 수 있습니다."),
    SHOP_RIDER_VISIT_GUIDE_CONTAINS_ADDRESS(400, "SHOP_RIDER_VISIT_GUIDE_CONTAINS_ADDRESS", "가게 주소는 라이더 안내에 등록할 수 없습니다."),
    SHOP_RIDER_VISIT_GUIDE_DISPATCH_RESTRICTION(400, "SHOP_RIDER_VISIT_GUIDE_DISPATCH_RESTRICTION", "배차나 이동수단을 특정하는 문구는 등록할 수 없습니다."),
    SHOP_RIDER_VISIT_GUIDE_NOT_FOUND(404, "SHOP_RIDER_VISIT_GUIDE_NOT_FOUND", "등록된 라이더 가게방문 안내가 없습니다."),
    SHOP_IMAGE_CHANGE_REQUEST_NOT_FOUND(404, "SHOP_IMAGE_CHANGE_REQUEST_NOT_FOUND", "존재하지 않는 이미지 변경 요청입니다."),
    SHOP_IMAGE_CHANGE_REQUEST_ALREADY_PENDING(409, "SHOP_IMAGE_CHANGE_REQUEST_ALREADY_PENDING", "이미 처리 대기 중인 이미지 변경 요청이 있습니다."),
    SHOP_CONTENT_BOARD_NOT_FOUND(404, "SHOP_CONTENT_BOARD_NOT_FOUND", "존재하지 않는 콘텐츠보드입니다."),
    SHOP_NOTICE_NOT_FOUND(404, "SHOP_NOTICE_NOT_FOUND", "존재하지 않는 점주 공지입니다."),

    SHOP_ORDER_NOTICE_NOT_FOUND(404, "SHOP_ORDER_NOTICE_NOT_FOUND", "주문안내를 찾을 수 없습니다."),
    SHOP_ORDER_NOTICE_CONTENT_REQUIRED(400, "SHOP_ORDER_NOTICE_CONTENT_REQUIRED", "주문안내 내용을 입력해 주세요."),
    SHOP_ORDER_NOTICE_CONTENT_TOO_LONG(400, "SHOP_ORDER_NOTICE_CONTENT_TOO_LONG", "주문안내는 500자 이내로 입력해 주세요."),

    SHOP_MENU_COLLECTION_IMAGE_NOT_FOUND(404, "SHOP_MENU_COLLECTION_IMAGE_NOT_FOUND", "메뉴모음컷을 찾을 수 없습니다."),
    SHOP_MENU_COLLECTION_IMAGE_LIMIT_EXCEEDED(400, "SHOP_MENU_COLLECTION_IMAGE_LIMIT_EXCEEDED", "메뉴모음컷은 최대 6개까지 등록할 수 있습니다."),
    SHOP_MENU_COLLECTION_IMAGE_LAST_CANNOT_DELETE(400, "SHOP_MENU_COLLECTION_IMAGE_LAST_CANNOT_DELETE", "메뉴모음컷은 최소 1개 이상 등록되어야 합니다."),
    SHOP_MENU_COLLECTION_IMAGE_ORDER_TARGET_MISMATCH(400, "SHOP_MENU_COLLECTION_IMAGE_ORDER_TARGET_MISMATCH", "목록이 최신 상태와 일치하지 않습니다. 새로고침 후 다시 시도해 주세요."),

    SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_NOT_FOUND(404, "SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_NOT_FOUND", "존재하지 않는 배달지역 조정 신청입니다."),
    SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_ALREADY_PENDING(409, "SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_ALREADY_PENDING", "이미 진행 중인 배달지역 조정 신청이 있습니다."),

    SHOP_REQUEST_NOT_FOUND(404, "SHOP_REQUEST_NOT_FOUND", "존재하지 않는 요청입니다."),
    SHOP_STORE_PRICE_VERIFICATION_NOT_FOUND(404, "SHOP_STORE_PRICE_VERIFICATION_NOT_FOUND", "매장 가격 인증 요청을 찾을 수 없습니다."),
    SHOP_STORE_PRICE_VERIFICATION_IN_PROGRESS(400, "SHOP_STORE_PRICE_VERIFICATION_IN_PROGRESS", "매장가격 검수 중에는 인증 요청을 할 수 없습니다."),
    SHOP_STORE_PRICE_VERIFICATION_DISCOUNT_IN_PROGRESS(400, "SHOP_STORE_PRICE_VERIFICATION_DISCOUNT_IN_PROGRESS", "할인 진행 중에는 인증 요청을 할 수 없습니다."),
    SHOP_STORE_PRICE_VERIFICATION_TARGET_EMPTY(400, "SHOP_STORE_PRICE_VERIFICATION_TARGET_EMPTY", "인증할 메뉴를 1개 이상 선택해야 합니다."),

    PRODUCT_NOT_FOUND(404, "PRODUCT_NOT_FOUND", "상품을 찾을 수 없습니다."),
    PRODUCT_PRICE_NOT_FOUND(404, "PRODUCT_PRICE_NOT_FOUND", "가격 정보를 찾을 수 없습니다."),
    PRODUCT_LAST_REPRESENTATIVE_CANNOT_HIDE(400, "PRODUCT_LAST_REPRESENTATIVE_CANNOT_HIDE", "사장님 추천 메뉴는 최소 1개 남아 있어야 합니다."),
    PRODUCT_AVAILABILITY_TARGET_EMPTY(400, "PRODUCT_AVAILABILITY_TARGET_EMPTY", "대상을 1개 이상 선택해야 합니다."),
    PRODUCT_ORDER_TARGET_MISMATCH(400, "PRODUCT_ORDER_TARGET_MISMATCH", "메뉴 목록이 최신 상태와 일치하지 않습니다. 새로고침 후 다시 시도해 주세요."),
    PRODUCT_OPTION_GROUP_NOT_FOUND(404, "PRODUCT_OPTION_GROUP_NOT_FOUND", "옵션그룹을 찾을 수 없습니다."),
    PRODUCT_IMAGE_NOT_FOUND(404, "PRODUCT_IMAGE_NOT_FOUND", "메뉴 이미지를 찾을 수 없습니다."),
    PRODUCT_IMAGE_CHANGE_REQUEST_NOT_FOUND(404, "PRODUCT_IMAGE_CHANGE_REQUEST_NOT_FOUND", "이미지 변경 요청을 찾을 수 없습니다."),
    PRODUCT_IMAGE_CHANGE_REQUEST_ALREADY_PENDING(400, "PRODUCT_IMAGE_CHANGE_REQUEST_ALREADY_PENDING", "이미 검수 대기 중인 이미지 변경 요청이 있습니다."),
    PRODUCT_VEGETARIAN_REQUEST_NOT_FOUND(404, "PRODUCT_VEGETARIAN_REQUEST_NOT_FOUND", "채식 설정 요청을 찾을 수 없습니다."),
    PRODUCT_VEGETARIAN_REQUEST_ALREADY_PENDING(400, "PRODUCT_VEGETARIAN_REQUEST_ALREADY_PENDING", "이미 검수 대기 중인 채식 설정 요청이 있습니다."),
    PRODUCT_VEGETARIAN_CATEGORY_NOT_ALLOWED(400, "PRODUCT_VEGETARIAN_CATEGORY_NOT_ALLOWED", "채식 메뉴를 등록할 수 없는 가게 카테고리입니다."),
    PRODUCT_REPRESENTATIVE_LIMIT_EXCEEDED(400, "PRODUCT_REPRESENTATIVE_LIMIT_EXCEEDED", "사장님 추천 메뉴는 최대 6개까지 등록할 수 있습니다."),
    PRODUCT_REPRESENTATIVE_IMAGE_REQUIRED(400, "PRODUCT_REPRESENTATIVE_IMAGE_REQUIRED", "이미지가 등록된 메뉴만 사장님 추천으로 설정할 수 있습니다."),
    PRODUCT_REPRESENTATIVE_REQUEST_NOT_FOUND(404, "PRODUCT_REPRESENTATIVE_REQUEST_NOT_FOUND", "사장님 추천 요청을 찾을 수 없습니다."),

    PRODUCT_FEEDBACK_ALREADY_SUBMITTED(400, "PRODUCT_FEEDBACK_ALREADY_SUBMITTED", "최근에 같은 의견을 보내셨습니다."),

    EVENT_NOT_FOUND(404, "EVENT_NOT_FOUND", "이벤트를 찾을 수 없습니다."),

    REFERRAL_NOT_FOUND(404, "REFERRAL_NOT_FOUND", "추천 이력을 찾을 수 없습니다.");

    private final int httpStatusCode;
    private final String code;
    private final String defaultMessage;

    ApplicationErrorCode(int httpStatusCode, String code, String defaultMessage) {
        this.httpStatusCode = httpStatusCode;
        this.code = code;
        this.defaultMessage = defaultMessage;
    }

    @Override
    public int getHttpStatusCode() {
        return this.httpStatusCode;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public String getDefaultMessage() {
        return this.defaultMessage;
    }
}
