plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    implementation project(':domain-module')
    implementation project(':application')

    implementation 'org.springframework:spring-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    implementation 'software.amazon.awssdk:ses'
    implementation 'software.amazon.awssdk:sns'
    implementation 'io.awspring.cloud:spring-cloud-aws-s3'
    implementation 'com.google.firebase:firebase-admin:9.10.0'
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
