logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%X{requestId:--}] [%thread] %cyan(%logger{36}) : %msg%n"
  level:
    root: INFO
    # INFO: 메타 정보만 로깅 (운영 환경) / DEBUG: Request/Response Body 추가 로깅 (개발 환경)
    com.tastyhouse.logging: ${API_BODY_LOG_LEVEL:DEBUG}

decorator:
  datasource:
    p6spy:
      log-format: "%(sql)"
