package com.tastyhouse.application.shared.exception;

public enum CeoErrorCode implements ApplicationErrorCodeSpec {

    CEO_USERNAME_DUPLICATED(409, "CEO_USERNAME_DUPLICATED", "이미 사용 중인 점주 아이디입니다."),
    CEO_AUTHENTICATION_FAILED(401, "CEO_AUTHENTICATION_FAILED", "아이디 또는 비밀번호가 올바르지 않습니다."),
    CEO_ACCOUNT_INACTIVE(401, "CEO_ACCOUNT_INACTIVE", "비활성화된 점주 계정입니다."),

    CEO_LOGIN_HISTORY_DATE_OUT_OF_RANGE(400, "CEO_LOGIN_HISTORY_DATE_OUT_OF_RANGE", "조회 가능한 기간은 최근 90일입니다."),
    CEO_SHOP_ACCESS_HISTORY_DATE_OUT_OF_RANGE(400, "CEO_SHOP_ACCESS_HISTORY_DATE_OUT_OF_RANGE", "조회 가능한 기간은 최근 5년입니다."),

    CEO_REPLY_PHRASE_NOT_FOUND(404, "CEO_REPLY_PHRASE_NOT_FOUND", "자주 쓰는 문구를 찾을 수 없습니다."),
    CEO_REPLY_PHRASE_LIMIT_EXCEEDED(409, "CEO_REPLY_PHRASE_LIMIT_EXCEEDED", "자주 쓰는 문구는 최대 5개까지 등록할 수 있습니다."),
    CEO_REPLY_PHRASE_ACCESS_DENIED(403, "CEO_REPLY_PHRASE_ACCESS_DENIED", "다른 점주의 문구입니다."),

    REVIEW_OWNER_REPLY_NOT_FOUND(404, "REVIEW_OWNER_REPLY_NOT_FOUND", "사장님 답변을 찾을 수 없습니다."),
    REVIEW_OWNER_REPLY_ALREADY_EXISTS(409, "REVIEW_OWNER_REPLY_ALREADY_EXISTS", "이미 답변을 등록한 리뷰입니다."),
    REVIEW_OWNER_REPLY_PERIOD_EXPIRED(400, "REVIEW_OWNER_REPLY_PERIOD_EXPIRED",
        "리뷰 작성일로부터 30일이 지나 답변을 등록할 수 없습니다."),
    REVIEW_DATE_RANGE_INVALID(400, "REVIEW_DATE_RANGE_INVALID", "조회 시작일이 종료일보다 늦을 수 없습니다."),

    SHOP_TEMPORARY_CLOSURE_NOT_FOUND(404, "SHOP_TEMPORARY_CLOSURE_NOT_FOUND", "존재하지 않는 임시 휴무입니다."),
    SHOP_TEMPORARY_CLOSURE_LIMIT_EXCEEDED(400, "SHOP_TEMPORARY_CLOSURE_LIMIT_EXCEEDED", "임시 휴무는 누적 30일을 초과할 수 없습니다."),
    SHOP_PHONE_NUMBER_NOT_FOUND(404, "SHOP_PHONE_NUMBER_NOT_FOUND", "존재하지 않는 가게 전화번호입니다."),
    SHOP_PHONE_NUMBER_LIMIT_EXCEEDED(400, "SHOP_PHONE_NUMBER_LIMIT_EXCEEDED", "가게 전화번호는 최대 10개까지 등록할 수 있습니다."),

    SHOP_SUSPENSION_NOT_FOUND(404, "SHOP_SUSPENSION_NOT_FOUND", "존재하지 않는 영업 임시중지입니다."),
    SHOP_CONTENT_BOARD_LIMIT_EXCEEDED(400, "SHOP_CONTENT_BOARD_LIMIT_EXCEEDED", "콘텐츠보드는 최대 4개까지 등록할 수 있습니다."),
    SHOP_NOTICE_IMAGE_LIMIT_EXCEEDED(400, "SHOP_NOTICE_IMAGE_LIMIT_EXCEEDED", "공지 이미지는 최대 3장까지 등록할 수 있습니다."),

    SHOP_MENU_COLLECTION_IMAGE_SPEC_INVALID(400, "SHOP_MENU_COLLECTION_IMAGE_SPEC_INVALID", "1280x960 이상, 15MB 이하의 JPG/PNG 이미지만 등록할 수 있습니다."),

    SHOP_DELIVERY_TIP_TIER_NOT_ASCENDING(400, "SHOP_DELIVERY_TIP_TIER_NOT_ASCENDING", "배달팁 구간의 주문금액은 오름차순이어야 합니다."),
    SHOP_DELIVERY_TIP_TIER_NOT_DESCENDING(400, "SHOP_DELIVERY_TIP_TIER_NOT_DESCENDING", "주문금액이 높은 구간의 배달팁은 더 낮아야 합니다."),
    SHOP_DELIVERY_TIP_EXTRA_TYPE_CONFLICT(409, "SHOP_DELIVERY_TIP_EXTRA_TYPE_CONFLICT", "거리별과 지역별 배달팁은 함께 사용할 수 없습니다."),
    SHOP_DELIVERY_TIP_REGION_NOT_IN_DELIVERY_AREA(400, "SHOP_DELIVERY_TIP_REGION_NOT_IN_DELIVERY_AREA", "배달가능지역으로 설정된 행정동만 선택할 수 있습니다."),
    SHOP_DELIVERY_TIP_REGION_DUPLICATED(409, "SHOP_DELIVERY_TIP_REGION_DUPLICATED", "이미 등록된 지역입니다."),

    SHOP_DELIVERY_AREA_NOT_FOUND(404, "SHOP_DELIVERY_AREA_NOT_FOUND", "배달가능지역을 찾을 수 없습니다."),
    SHOP_DELIVERY_AREA_DUPLICATED(409, "SHOP_DELIVERY_AREA_DUPLICATED", "이미 등록된 배달가능지역입니다."),
    SHOP_DELIVERY_AREA_IN_USE(409, "SHOP_DELIVERY_AREA_IN_USE", "지역별 배달팁이 설정된 지역은 삭제할 수 없습니다."),
    ADMIN_DONG_NOT_FOUND(404, "ADMIN_DONG_NOT_FOUND", "행정동을 찾을 수 없습니다."),
    ADMIN_DONG_QUERY_INVALID(400, "ADMIN_DONG_QUERY_INVALID", "행정동 조회 조건이 올바르지 않습니다."),
    SHOP_DELIVERY_AREA_EMPTY_PROJECTION(400, "SHOP_DELIVERY_AREA_EMPTY_PROJECTION", "선택한 영역에 포함되는 행정동이 없습니다."),

    SHOP_STORE_PRICE_LIST_IMAGE_SPEC_INVALID(400, "SHOP_STORE_PRICE_LIST_IMAGE_SPEC_INVALID", "750 × 350 이상, 15MB 이하의 JPG/PNG 이미지만 등록할 수 있습니다."),
    SHOP_REQUEST_DATE_RANGE_INVALID(400, "SHOP_REQUEST_DATE_RANGE_INVALID", "조회 시작일이 종료일보다 늦습니다."),

    SHOP_CHANGE_HISTORY_DATE_OUT_OF_RANGE(400, "SHOP_CHANGE_HISTORY_DATE_OUT_OF_RANGE", "조회 가능한 기간은 최근 6개월입니다."),

    PRODUCT_PRICE_EMPTY(400, "PRODUCT_PRICE_EMPTY", "가격은 1개 이상 등록해야 합니다."),
    PRODUCT_PRICE_NAME_DUPLICATED(400, "PRODUCT_PRICE_NAME_DUPLICATED", "이미 사용 중인 가격명입니다."),
    PRODUCT_PRICE_STORE_NOT_VERIFIED(400, "PRODUCT_PRICE_STORE_NOT_VERIFIED", "매장 가격 인증 후에 매장가격·픽업가격을 설정할 수 있습니다."),
    PRODUCT_PRICE_DISCOUNT_IN_PROGRESS(400, "PRODUCT_PRICE_DISCOUNT_IN_PROGRESS", "할인이 대기·진행 중인 메뉴는 가격을 변경할 수 없습니다."),
    PRODUCT_SOLD_OUT_UNTIL_TOO_SOON(400, "PRODUCT_SOLD_OUT_UNTIL_TOO_SOON", "품절 기간은 현재 시각으로부터 30분 이후여야 합니다."),
    PRODUCT_SOLD_OUT_UNTIL_TOO_FAR(400, "PRODUCT_SOLD_OUT_UNTIL_TOO_FAR", "품절 기간은 최대 7일 이내여야 합니다."),
    PRODUCT_LAST_VISIBLE_CANNOT_HIDE(400, "PRODUCT_LAST_VISIBLE_CANNOT_HIDE", "가게 메뉴판에는 최소 1개 메뉴가 노출되어야 합니다."),
    PRODUCT_NAME_DUPLICATED(400, "PRODUCT_NAME_DUPLICATED", "이미 사용 중인 메뉴명입니다."),
    PRODUCT_NAME_INVALID_CHARACTER(400, "PRODUCT_NAME_INVALID_CHARACTER", "메뉴명에 사용할 수 없는 특수문자가 포함되어 있습니다."),
    PRODUCT_CATEGORY_NOT_FOUND(404, "PRODUCT_CATEGORY_NOT_FOUND", "메뉴그룹을 찾을 수 없습니다."),
    PRODUCT_CATEGORY_HAS_PRODUCTS(400, "PRODUCT_CATEGORY_HAS_PRODUCTS", "소속된 메뉴가 있어 메뉴그룹을 삭제할 수 없습니다."),
    PRODUCT_CATEGORY_ORDER_TARGET_MISMATCH(400, "PRODUCT_CATEGORY_ORDER_TARGET_MISMATCH", "메뉴그룹 목록이 최신 상태와 일치하지 않습니다. 새로고침 후 다시 시도해 주세요."),
    PRODUCT_OPTION_NOT_FOUND(404, "PRODUCT_OPTION_NOT_FOUND", "옵션을 찾을 수 없습니다."),
    PRODUCT_OPTION_GROUP_SHOP_MISMATCH(400, "PRODUCT_OPTION_GROUP_SHOP_MISMATCH", "다른 가게의 옵션그룹은 연결할 수 없습니다."),
    PRODUCT_OPTION_GROUP_LAST_LINK_CANNOT_UNLINK(400, "PRODUCT_OPTION_GROUP_LAST_LINK_CANNOT_UNLINK", "옵션그룹의 마지막 연결은 해제할 수 없습니다."),
    PRODUCT_OPTION_GROUP_SELECT_RANGE_INVALID(400, "PRODUCT_OPTION_GROUP_SELECT_RANGE_INVALID", "최소 선택 개수는 최대 선택 개수보다 클 수 없습니다."),
    PRODUCT_OPTION_GROUP_MERGE_TARGET_EMPTY(400, "PRODUCT_OPTION_GROUP_MERGE_TARGET_EMPTY", "합칠 옵션그룹을 1개 이상 선택해야 합니다."),
    PRODUCT_OPTION_GROUP_MERGE_BASE_INCLUDED(400, "PRODUCT_OPTION_GROUP_MERGE_BASE_INCLUDED", "기준 옵션그룹은 합칠 대상에 포함할 수 없습니다."),
    PRODUCT_OPTION_GROUP_MERGE_SAME_PRODUCT_LINKED(400, "PRODUCT_OPTION_GROUP_MERGE_SAME_PRODUCT_LINKED", "같은 메뉴에 연결된 옵션그룹끼리는 합칠 수 없습니다."),
    PRODUCT_OPTION_GROUP_MERGE_HIDDEN_TARGET(400, "PRODUCT_OPTION_GROUP_MERGE_HIDDEN_TARGET", "삭제된 옵션그룹은 합칠 수 없습니다."),
    PRODUCT_OPTION_GROUP_MERGE_SIGNATURE_MISMATCH(400, "PRODUCT_OPTION_GROUP_MERGE_SIGNATURE_MISMATCH", "추천 목록이 최신 상태와 일치하지 않습니다. 새로고침 후 다시 시도해 주세요."),
    PRODUCT_OPTION_GROUP_MERGE_TYPE_MISMATCH(400, "PRODUCT_OPTION_GROUP_MERGE_TYPE_MISMATCH", "일회용컵 보증금 옵션그룹은 일반 옵션그룹과 합칠 수 없습니다."),
    PRODUCT_EXPOSURE_DAY_TYPE_MIXED(400, "PRODUCT_EXPOSURE_DAY_TYPE_MIXED", "요일 묶음과 개별 요일은 함께 설정할 수 없습니다."),
    PRODUCT_IMAGE_SPEC_INVALID(400, "PRODUCT_IMAGE_SPEC_INVALID", "메뉴 이미지 규격에 맞지 않습니다."),
    PRODUCT_NUTRITION_NOT_FOUND(404, "PRODUCT_NUTRITION_NOT_FOUND", "영양성분 정보를 찾을 수 없습니다."),

    PRODUCT_SHOP_LINK_NOT_FOUND(404, "PRODUCT_SHOP_LINK_NOT_FOUND", "메뉴-가게 연결을 찾을 수 없습니다."),
    PRODUCT_SHOP_LINK_NOT_OWNED(400, "PRODUCT_SHOP_LINK_NOT_OWNED", "본인 소유 가게에만 연결할 수 있습니다."),
    PRODUCT_SHOP_LINK_LAST_CANNOT_UNLINK(400, "PRODUCT_SHOP_LINK_LAST_CANNOT_UNLINK", "메뉴는 최소 1개 가게에 연결되어야 합니다."),
    PRODUCT_SHOP_LINK_CATEGORY_REQUIRED(400, "PRODUCT_SHOP_LINK_CATEGORY_REQUIRED", "메뉴가 노출될 메뉴그룹을 선택해 주세요."),
    PRODUCT_SHOP_LINK_CATEGORY_MISMATCH(400, "PRODUCT_SHOP_LINK_CATEGORY_MISMATCH", "해당 가게의 메뉴그룹이 아닙니다."),
    PRODUCT_SHOP_LINK_ALREADY_LINKED(400, "PRODUCT_SHOP_LINK_ALREADY_LINKED", "이미 연결된 가게입니다.");

    private final int httpStatusCode;
    private final String code;
    private final String defaultMessage;

    CeoErrorCode(int httpStatusCode, String code, String defaultMessage) {
        this.httpStatusCode = httpStatusCode;
        this.code = code;
        this.defaultMessage = defaultMessage;
    }

    @Override
    public int getHttpStatusCode() {
        return this.httpStatusCode;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public String getDefaultMessage() {
        return this.defaultMessage;
    }
}
