package com.tastyhouse.core.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    // 공통 - 엔티티 미존재
    ENTITY_NOT_FOUND(404, "ENTITY_NOT_FOUND", "요청한 데이터를 찾을 수 없습니다."),

    // 주문
    ORDER_NOT_FOUND(404, "ORDER_NOT_FOUND", "주문을 찾을 수 없습니다."),
    ORDER_ACCESS_DENIED(403, "ORDER_ACCESS_DENIED", "본인의 주문만 조회할 수 있습니다."),
    ORDER_PRODUCT_NOT_FOUND(404, "ORDER_PRODUCT_NOT_FOUND", "상품을 찾을 수 없습니다."),
    ORDER_OPTION_GROUP_NOT_FOUND(404, "ORDER_OPTION_GROUP_NOT_FOUND", "옵션 그룹을 찾을 수 없습니다."),
    ORDER_OPTION_NOT_FOUND(404, "ORDER_OPTION_NOT_FOUND", "옵션을 찾을 수 없습니다."),
    ORDER_PRODUCT_SOLD_OUT(400, "ORDER_PRODUCT_SOLD_OUT", "품절된 상품입니다."),
    ORDER_PRODUCT_AMOUNT_MISMATCH(400, "ORDER_PRODUCT_AMOUNT_MISMATCH", "상품 금액이 일치하지 않습니다."),
    ORDER_PRODUCT_DISCOUNT_AMOUNT_MISMATCH(400, "ORDER_PRODUCT_DISCOUNT_AMOUNT_MISMATCH", "상품 할인 금액이 일치하지 않습니다."),
    ORDER_COUPON_DISCOUNT_AMOUNT_MISMATCH(400, "ORDER_COUPON_DISCOUNT_AMOUNT_MISMATCH", "쿠폰 사용 금액이 일치하지 않습니다."),
    ORDER_POINT_DISCOUNT_AMOUNT_MISMATCH(400, "ORDER_POINT_DISCOUNT_AMOUNT_MISMATCH", "포인트 사용 금액이 일치하지 않습니다."),
    ORDER_TOTAL_DISCOUNT_AMOUNT_MISMATCH(400, "ORDER_TOTAL_DISCOUNT_AMOUNT_MISMATCH", "할인 금액이 일치하지 않습니다."),
    ORDER_FINAL_AMOUNT_MISMATCH(400, "ORDER_FINAL_AMOUNT_MISMATCH", "결제 금액이 일치하지 않습니다."),
    ORDER_MINIMUM_AMOUNT_NOT_MET(400, "ORDER_MINIMUM_AMOUNT_NOT_MET", "최소 주문 금액을 충족하지 않습니다."),
    ORDER_METHOD_UNKNOWN(400, "ORDER_METHOD_UNKNOWN", "알 수 없는 주문 방법입니다."),
    ORDER_STATUS_UNKNOWN(400, "ORDER_STATUS_UNKNOWN", "알 수 없는 주문 상태입니다."),

    // 쿠폰
    COUPON_NOT_FOUND(404, "COUPON_NOT_FOUND", "쿠폰을 찾을 수 없습니다."),
    COUPON_ACCESS_DENIED(403, "COUPON_ACCESS_DENIED", "본인의 쿠폰만 사용할 수 있습니다."),
    COUPON_INFO_NOT_FOUND(404, "COUPON_INFO_NOT_FOUND", "쿠폰 정보를 찾을 수 없습니다."),
    COUPON_NOT_AVAILABLE(400, "COUPON_NOT_AVAILABLE", "사용할 수 없는 쿠폰입니다."),
    COUPON_DISCOUNT_TYPE_UNKNOWN(400, "COUPON_DISCOUNT_TYPE_UNKNOWN", "알 수 없는 할인 유형입니다."),
    COUPON_ALREADY_ISSUED(409, "COUPON_ALREADY_ISSUED", "이미 발급된 쿠폰입니다."),

    // 결제
    PAYMENT_ORDER_ACCESS_DENIED(403, "PAYMENT_ORDER_ACCESS_DENIED", "본인의 주문만 결제할 수 있습니다."),
    PAYMENT_ACCESS_DENIED(403, "PAYMENT_ACCESS_DENIED", "본인의 결제만 처리할 수 있습니다."),
    PAYMENT_INVALID_ORDER_STATUS(400, "PAYMENT_INVALID_ORDER_STATUS", "결제할 수 없는 주문 상태입니다."),
    PAYMENT_ALREADY_IN_PROGRESS(400, "PAYMENT_ALREADY_IN_PROGRESS", "이미 결제가 진행 중인 주문입니다."),
    PAYMENT_NOT_PENDING_APPROVAL(400, "PAYMENT_NOT_PENDING_APPROVAL", "승인 대기 중인 결제만 처리할 수 있습니다."),
    PAYMENT_AMOUNT_MISMATCH(400, "PAYMENT_AMOUNT_MISMATCH", "결제 금액이 일치하지 않습니다."),
    PAYMENT_APPROVAL_FAILED(400, "PAYMENT_APPROVAL_FAILED", "결제 승인에 실패했습니다."),
    PAYMENT_REFUND_AMOUNT_EXCEEDED(400, "PAYMENT_REFUND_AMOUNT_EXCEEDED", "환불 금액이 결제 금액을 초과할 수 없습니다."),
    PAYMENT_NOT_COMPLETED(400, "PAYMENT_NOT_COMPLETED", "완료된 결제만 환불할 수 있습니다."),
    PAYMENT_NOT_PENDING(400, "PAYMENT_NOT_PENDING", "대기 중인 결제만 완료 처리할 수 있습니다."),
    PAYMENT_NOT_ON_SITE(400, "PAYMENT_NOT_ON_SITE", "현장결제만 완료 처리할 수 있습니다."),
    PAYMENT_METHOD_UNKNOWN(400, "PAYMENT_METHOD_UNKNOWN", "알 수 없는 결제 방법입니다."),
    PG_PROVIDER_UNKNOWN(400, "PG_PROVIDER_UNKNOWN", "알 수 없는 PG사입니다."),

    // 회원
    MEMBER_NOT_FOUND(404, "MEMBER_NOT_FOUND", "회원을 찾을 수 없습니다."),
    MEMBER_USERNAME_DUPLICATED(409, "MEMBER_USERNAME_DUPLICATED", "이미 사용 중인 아이디입니다."),
    MEMBER_EMAIL_ALREADY_REGISTERED(409, "MEMBER_EMAIL_ALREADY_REGISTERED", "이미 가입된 이메일입니다."),
    MEMBER_NICKNAME_DUPLICATED(409, "MEMBER_NICKNAME_DUPLICATED", "이미 사용 중인 닉네임입니다."),
    MEMBER_PHONE_ALREADY_REGISTERED(409, "MEMBER_PHONE_ALREADY_REGISTERED", "이미 가입된 휴대폰번호입니다."),
    MEMBER_SIGNUP_PHONE_REQUIRED(400, "MEMBER_SIGNUP_PHONE_REQUIRED", "회원가입 시 휴대폰 인증이 필요합니다."),
    MEMBER_SIGNUP_EMAIL_REQUIRED(400, "MEMBER_SIGNUP_EMAIL_REQUIRED", "회원가입 시 이메일 인증이 필요합니다."),
    MEMBER_INFO_AUTH_EXPIRED(400, "MEMBER_INFO_AUTH_EXPIRED", "개인정보 수정 인증이 만료되었습니다. 비밀번호를 다시 인증해주세요."),
    MEMBER_PHONE_SMS_REQUIRED(400, "MEMBER_PHONE_SMS_REQUIRED", "휴대폰번호 변경 시 SMS 인증이 필요합니다."),
    MEMBER_PHONE_AUTH_EXPIRED(400, "MEMBER_PHONE_AUTH_EXPIRED", "휴대폰 인증이 만료되었습니다. SMS 인증을 다시 진행해주세요."),
    MEMBER_PHONE_MISMATCH(400, "MEMBER_PHONE_MISMATCH", "인증된 휴대폰번호와 입력한 휴대폰번호가 일치하지 않습니다."),
    MEMBER_EMAIL_AUTH_EXPIRED(400, "MEMBER_EMAIL_AUTH_EXPIRED", "이메일 인증이 만료되었습니다. 이메일 인증을 다시 진행해주세요."),
    MEMBER_EMAIL_MISMATCH(400, "MEMBER_EMAIL_MISMATCH", "인증된 이메일과 입력한 아이디(이메일)가 일치하지 않습니다."),
    MEMBER_PASSWORD_MISMATCH(400, "MEMBER_PASSWORD_MISMATCH", "비밀번호가 일치하지 않습니다."),
    MEMBER_PASSWORD_CONFIRM_MISMATCH(400, "MEMBER_PASSWORD_CONFIRM_MISMATCH", "새 비밀번호와 비밀번호 확인이 일치하지 않습니다."),
    MEMBER_PASSWORD_SAME_AS_OLD(400, "MEMBER_PASSWORD_SAME_AS_OLD", "현재 비밀번호와 동일한 비밀번호로 변경할 수 없습니다."),
    MEMBER_PASSWORD_RESET_TOKEN_INVALID(400, "MEMBER_PASSWORD_RESET_TOKEN_INVALID", "비밀번호 재설정 토큰이 유효하지 않거나 만료되었습니다."),
    MEMBER_COUPON_NOT_FOUND(404, "MEMBER_COUPON_NOT_FOUND", "회원 쿠폰을 찾을 수 없습니다."),
    ALREADY_WITHDRAWN(409, "ALREADY_WITHDRAWN", "이미 탈퇴한 회원입니다."),
    MEMBER_ALREADY_SUSPENDED(409, "MEMBER_ALREADY_SUSPENDED", "이미 정지된 회원입니다."),
    MEMBER_ALREADY_ACTIVE(409, "MEMBER_ALREADY_ACTIVE", "이미 활성 상태인 회원입니다."),
    MEMBER_STATUS_CHANGE_NOT_ALLOWED(400, "MEMBER_STATUS_CHANGE_NOT_ALLOWED", "탈퇴한 회원은 상태를 변경할 수 없습니다."),

    // 관리자
    ADMIN_NOT_FOUND(404, "ADMIN_NOT_FOUND", "관리자를 찾을 수 없습니다."),
    ADMIN_USERNAME_DUPLICATED(409, "ADMIN_USERNAME_DUPLICATED", "이미 사용 중인 관리자 아이디입니다."),
    ADMIN_AUTHENTICATION_FAILED(401, "ADMIN_AUTHENTICATION_FAILED", "아이디 또는 비밀번호가 올바르지 않습니다."),
    ADMIN_ACCOUNT_INACTIVE(401, "ADMIN_ACCOUNT_INACTIVE", "비활성화된 관리자 계정입니다."),
    ADMIN_ROLE_UNKNOWN(400, "ADMIN_ROLE_UNKNOWN", "알 수 없는 관리자 권한입니다."),

    // 점주
    CEO_NOT_FOUND(404, "CEO_NOT_FOUND", "점주를 찾을 수 없습니다."),
    CEO_USERNAME_DUPLICATED(409, "CEO_USERNAME_DUPLICATED", "이미 사용 중인 점주 아이디입니다."),
    CEO_AUTHENTICATION_FAILED(401, "CEO_AUTHENTICATION_FAILED", "아이디 또는 비밀번호가 올바르지 않습니다."),
    CEO_ACCOUNT_INACTIVE(401, "CEO_ACCOUNT_INACTIVE", "비활성화된 점주 계정입니다."),

    // 인증 (SMS)
    VERIFICATION_CODE_NOT_FOUND(400, "VERIFICATION_CODE_NOT_FOUND", "발송된 인증번호가 없습니다. 인증번호를 다시 요청해주세요."),
    VERIFICATION_CODE_EXPIRED(400, "VERIFICATION_CODE_EXPIRED", "인증번호가 만료되었습니다. 인증번호를 다시 요청해주세요."),
    VERIFICATION_CODE_MISMATCH(400, "VERIFICATION_CODE_MISMATCH", "인증번호가 일치하지 않습니다."),

    // 인증 (이메일)
    EMAIL_VERIFICATION_CODE_NOT_FOUND(400, "EMAIL_VERIFICATION_CODE_NOT_FOUND", "발송된 인증번호가 없습니다. 인증번호를 다시 요청해주세요."),
    EMAIL_VERIFICATION_CODE_EXPIRED(400, "EMAIL_VERIFICATION_CODE_EXPIRED", "인증번호가 만료되었습니다. 인증번호를 다시 요청해주세요."),
    EMAIL_VERIFICATION_CODE_MISMATCH(400, "EMAIL_VERIFICATION_CODE_MISMATCH", "인증번호가 일치하지 않습니다."),

    // 포인트
    POINT_NOT_FOUND(404, "POINT_NOT_FOUND", "포인트 정보를 찾을 수 없습니다."),
    POINT_INSUFFICIENT(400, "POINT_INSUFFICIENT", "포인트가 부족합니다."),
    POINT_TYPE_UNKNOWN(400, "POINT_TYPE_UNKNOWN", "알 수 없는 포인트 유형입니다."),

    // 파일
    FILE_EMPTY(400, "FILE_EMPTY", "파일이 비어있습니다."),
    FILE_SIZE_EXCEEDED(400, "FILE_SIZE_EXCEEDED", "파일 크기는 10MB를 초과할 수 없습니다."),
    FILE_TYPE_NOT_ALLOWED(400, "FILE_TYPE_NOT_ALLOWED", "허용되지 않는 파일 형식입니다. (jpg, png, gif, webp만 가능)"),
    FILE_EXTENSION_NOT_ALLOWED(400, "FILE_EXTENSION_NOT_ALLOWED", "허용되지 않는 파일 확장자입니다. (jpg, png, gif, webp만 가능)"),
    FILE_EXTENSION_UNKNOWN(400, "FILE_EXTENSION_UNKNOWN", "파일 확장자를 확인할 수 없습니다."),
    FILE_NOT_FOUND(404, "FILE_NOT_FOUND", "파일을 찾을 수 없습니다."),
    FILE_STORE_FAILED(500, "FILE_STORE_FAILED", "파일 저장에 실패했습니다."),
    FILE_DELETE_FAILED(500, "FILE_DELETE_FAILED", "파일 삭제에 실패했습니다."),

    // 리뷰
    REVIEW_NOT_FOUND(404, "REVIEW_NOT_FOUND", "리뷰를 찾을 수 없습니다."),
    REVIEW_ACCESS_DENIED(403, "REVIEW_ACCESS_DENIED", "본인의 리뷰만 수정/삭제할 수 있습니다."),
    REVIEW_ALREADY_EXISTS(400, "REVIEW_ALREADY_EXISTS", "이미 리뷰를 작성한 상품입니다."),
    REVIEW_ORDER_PRODUCT_NOT_FOUND(404, "REVIEW_ORDER_PRODUCT_NOT_FOUND", "주문 상품을 찾을 수 없습니다."),
    REVIEW_ORDER_ACCESS_DENIED(403, "REVIEW_ORDER_ACCESS_DENIED", "본인의 주문에 대해서만 리뷰를 작성할 수 있습니다."),
    REVIEW_LIST_TYPE_UNKNOWN(400, "REVIEW_LIST_TYPE_UNKNOWN", "알 수 없는 리뷰 목록 조회 타입입니다."),
    REVIEW_COMMENT_NOT_FOUND(404, "REVIEW_COMMENT_NOT_FOUND", "댓글을 찾을 수 없습니다."),
    REVIEW_REPLY_NOT_FOUND(404, "REVIEW_REPLY_NOT_FOUND", "답글을 찾을 수 없습니다."),

    // 가게
    SHOP_NOT_FOUND(404, "SHOP_NOT_FOUND", "존재하지 않는 가게입니다."),
    STATION_NOT_FOUND(404, "STATION_NOT_FOUND", "존재하지 않는 지하철역입니다."),
    SHOP_AMENITY_CATEGORY_NOT_FOUND(404, "SHOP_AMENITY_CATEGORY_NOT_FOUND", "존재하지 않는 편의시설 카테고리입니다."),
    SHOP_IMAGE_CATEGORY_NOT_FOUND(404, "SHOP_IMAGE_CATEGORY_NOT_FOUND", "존재하지 않는 이미지 카테고리입니다."),
    SHOP_FOOD_TYPE_CATEGORY_NOT_FOUND(404, "SHOP_FOOD_TYPE_CATEGORY_NOT_FOUND", "존재하지 않는 음식 종류 카테고리입니다."),
    SHOP_BUSINESS_HOUR_NOT_FOUND(404, "SHOP_BUSINESS_HOUR_NOT_FOUND", "존재하지 않는 운영시간입니다."),
    SHOP_BREAK_TIME_NOT_FOUND(404, "SHOP_BREAK_TIME_NOT_FOUND", "존재하지 않는 브레이크타임입니다."),
    SHOP_CLOSED_DAY_NOT_FOUND(404, "SHOP_CLOSED_DAY_NOT_FOUND", "존재하지 않는 정기 휴무일입니다."),
    SHOP_AMENITY_NOT_FOUND(404, "SHOP_AMENITY_NOT_FOUND", "존재하지 않는 가게 편의시설입니다."),
    SHOP_FOOD_TYPE_NOT_FOUND(404, "SHOP_FOOD_TYPE_NOT_FOUND", "존재하지 않는 가게 음식 종류입니다."),
    TAG_NOT_FOUND(404, "TAG_NOT_FOUND", "존재하지 않는 태그입니다."),
    SHOP_ORDER_METHOD_NOT_FOUND(404, "SHOP_ORDER_METHOD_NOT_FOUND", "존재하지 않는 가게 주문수단입니다."),
    SHOP_BANNER_IMAGE_NOT_FOUND(404, "SHOP_BANNER_IMAGE_NOT_FOUND", "존재하지 않는 배너 이미지입니다."),
    SHOP_PHOTO_CATEGORY_NOT_FOUND(404, "SHOP_PHOTO_CATEGORY_NOT_FOUND", "존재하지 않는 포토 카테고리입니다."),
    SHOP_PHOTO_CATEGORY_IMAGE_NOT_FOUND(404, "SHOP_PHOTO_CATEGORY_IMAGE_NOT_FOUND", "존재하지 않는 포토 이미지입니다."),
    SHOP_CHOICE_NOT_FOUND(404, "SHOP_CHOICE_NOT_FOUND", "존재하지 않는 테하 초이스입니다."),
    DAY_TYPE_UNKNOWN(400, "DAY_TYPE_UNKNOWN", "알 수 없는 요일 유형입니다."),
    CLOSED_DAY_TYPE_UNKNOWN(400, "CLOSED_DAY_TYPE_UNKNOWN", "알 수 없는 정기 휴무 유형입니다."),

    // 점주 가게 관리 (ceo-api)
    SHOP_ACCESS_DENIED(403, "SHOP_ACCESS_DENIED", "해당 가게에 대한 접근 권한이 없습니다."),
    SHOP_BUSINESS_HOUR_INVALID_UNIT(400, "SHOP_BUSINESS_HOUR_INVALID_UNIT", "영업시간은 5분 단위로 설정해야 합니다."),
    SHOP_BUSINESS_HOUR_INVALID_RANGE(400, "SHOP_BUSINESS_HOUR_INVALID_RANGE", "영업시간은 최소 1시간, 최대 23시간 55분이어야 합니다."),
    SHOP_BUSINESS_HOUR_OVERLAP(400, "SHOP_BUSINESS_HOUR_OVERLAP", "요일별 영업시간이 서로 겹칠 수 없습니다."),
    SHOP_BREAK_TIME_OUT_OF_BUSINESS_HOURS(400, "SHOP_BREAK_TIME_OUT_OF_BUSINESS_HOURS", "휴게시간은 영업시간 범위 안에서만 설정할 수 있습니다."),
    SHOP_BREAK_TIME_EQUALS_BUSINESS_HOURS(400, "SHOP_BREAK_TIME_EQUALS_BUSINESS_HOURS", "휴게시간을 영업시간과 완전히 동일하게 설정할 수 없습니다."),
    SHOP_REGULAR_CLOSED_DAY_LIMIT_EXCEEDED(400, "SHOP_REGULAR_CLOSED_DAY_LIMIT_EXCEEDED", "정기 휴무일은 최대 15개까지 설정할 수 있습니다."),
    SHOP_TEMPORARY_CLOSURE_NOT_FOUND(404, "SHOP_TEMPORARY_CLOSURE_NOT_FOUND", "존재하지 않는 임시 휴무입니다."),
    SHOP_TEMPORARY_CLOSURE_INVALID_PERIOD(400, "SHOP_TEMPORARY_CLOSURE_INVALID_PERIOD", "임시 휴무 종료일은 시작일과 같거나 이후여야 합니다."),
    SHOP_TEMPORARY_CLOSURE_LIMIT_EXCEEDED(400, "SHOP_TEMPORARY_CLOSURE_LIMIT_EXCEEDED", "임시 휴무는 누적 30일을 초과할 수 없습니다."),
    SHOP_PHONE_NUMBER_NOT_FOUND(404, "SHOP_PHONE_NUMBER_NOT_FOUND", "존재하지 않는 가게 전화번호입니다."),
    SHOP_PHONE_NUMBER_LIMIT_EXCEEDED(400, "SHOP_PHONE_NUMBER_LIMIT_EXCEEDED", "가게 전화번호는 최대 10개까지 등록할 수 있습니다."),
    SHOP_PHONE_NUMBER_PRIMARY_REQUIRED(400, "SHOP_PHONE_NUMBER_PRIMARY_REQUIRED", "대표 전화번호는 반드시 1개 지정되어야 합니다."),
    SHOP_VIRTUAL_NUMBER_INVALID(400, "SHOP_VIRTUAL_NUMBER_INVALID", "가상번호 발급 조건(지정 국번, 8~13자리)을 충족하지 않습니다."),
    SHOP_STATUS_CHANGE_BLOCKED_BY_PENDING_REQUEST(409, "SHOP_STATUS_CHANGE_BLOCKED_BY_PENDING_REQUEST", "진행 중인 승인 요청이 있어 가게 상태를 변경할 수 없습니다."),
    SHOP_TEXT_PROHIBITED_WORD(400, "SHOP_TEXT_PROHIBITED_WORD", "등록할 수 없는 문구가 포함되어 있습니다."),
    SHOP_INTRODUCTION_TOO_LONG(400, "SHOP_INTRODUCTION_TOO_LONG", "가게 소개는 최대 500자까지 입력할 수 있습니다."),
    SHOP_DIRECTIONS_GUIDE_TOO_LONG(400, "SHOP_DIRECTIONS_GUIDE_TOO_LONG", "찾아오는 길 안내는 최대 200자까지 입력할 수 있습니다."),
    SHOP_DISPLAY_LOCATION_OUT_OF_RANGE(400, "SHOP_DISPLAY_LOCATION_OUT_OF_RANGE", "노출 위치는 실제 위치 반경 1km 이내에서만 변경할 수 있습니다."),
    SHOP_CONVENIENCE_INFO_NOT_FOUND(404, "SHOP_CONVENIENCE_INFO_NOT_FOUND", "존재하지 않는 가게 편의정보입니다."),
    SHOP_IMAGE_CHANGE_REQUEST_NOT_FOUND(404, "SHOP_IMAGE_CHANGE_REQUEST_NOT_FOUND", "존재하지 않는 이미지 변경 요청입니다."),
    SHOP_IMAGE_CHANGE_REQUEST_ALREADY_PENDING(409, "SHOP_IMAGE_CHANGE_REQUEST_ALREADY_PENDING", "이미 처리 대기 중인 이미지 변경 요청이 있습니다."),
    SHOP_IMAGE_CHANGE_REQUEST_NOT_PENDING(409, "SHOP_IMAGE_CHANGE_REQUEST_NOT_PENDING", "대기 상태가 아닌 요청은 처리할 수 없습니다."),
    SHOP_IMAGE_SPEC_INVALID(400, "SHOP_IMAGE_SPEC_INVALID", "이미지 규격(형식/용량/해상도/비율)을 충족하지 않습니다."),
    SHOP_IMAGE_TYPE_UNKNOWN(400, "SHOP_IMAGE_TYPE_UNKNOWN", "알 수 없는 이미지 유형입니다."),
    SHOP_SUSPENSION_NOT_FOUND(404, "SHOP_SUSPENSION_NOT_FOUND", "존재하지 않는 영업 임시중지입니다."),
    SHOP_SUSPENSION_INVALID_PERIOD(400, "SHOP_SUSPENSION_INVALID_PERIOD", "임시중지 종료시간은 시작시간 이후여야 합니다."),
    SHOP_SUSPENSION_REASON_UNKNOWN(400, "SHOP_SUSPENSION_REASON_UNKNOWN", "알 수 없는 임시중지 사유입니다."),
    SHOP_CONTENT_BOARD_NOT_FOUND(404, "SHOP_CONTENT_BOARD_NOT_FOUND", "존재하지 않는 콘텐츠보드입니다."),
    SHOP_CONTENT_BOARD_LIMIT_EXCEEDED(400, "SHOP_CONTENT_BOARD_LIMIT_EXCEEDED", "콘텐츠보드는 최대 4개까지 등록할 수 있습니다."),
    SHOP_CONTENT_TYPE_UNKNOWN(400, "SHOP_CONTENT_TYPE_UNKNOWN", "알 수 없는 콘텐츠 형태입니다."),
    SHOP_CONTENT_TOPIC_UNKNOWN(400, "SHOP_CONTENT_TOPIC_UNKNOWN", "알 수 없는 콘텐츠 주제입니다."),
    SHOP_CONTENT_DESCRIPTION_TOO_LONG(400, "SHOP_CONTENT_DESCRIPTION_TOO_LONG", "콘텐츠 설명글은 최대 50자까지 입력할 수 있습니다."),
    SHOP_CONTENT_YOUTUBE_URL_INVALID(400, "SHOP_CONTENT_YOUTUBE_URL_INVALID", "유효한 유튜브 링크가 아닙니다."),
    SHOP_HYGIENE_BADGE_NOT_FOUND(404, "SHOP_HYGIENE_BADGE_NOT_FOUND", "존재하지 않는 위생 인증 뱃지입니다."),
    HYGIENE_BADGE_TYPE_UNKNOWN(400, "HYGIENE_BADGE_TYPE_UNKNOWN", "알 수 없는 위생 인증 유형입니다."),

    // 정책
    POLICY_NOT_FOUND(404, "POLICY_NOT_FOUND", "정책 문서를 찾을 수 없습니다."),
    POLICY_CURRENT_NOT_FOUND(404, "POLICY_CURRENT_NOT_FOUND", "현재 유효한 정책을 찾을 수 없습니다."),
    POLICY_VERSION_NOT_FOUND(404, "POLICY_VERSION_NOT_FOUND", "해당 버전의 정책을 찾을 수 없습니다."),
    POLICY_TYPE_UNKNOWN(400, "POLICY_TYPE_UNKNOWN", "알 수 없는 정책 타입입니다."),

    // 상품
    PRODUCT_NOT_FOUND(404, "PRODUCT_NOT_FOUND", "상품을 찾을 수 없습니다."),

    // 공지사항
    NOTICE_NOT_FOUND(404, "NOTICE_NOT_FOUND", "공지사항을 찾을 수 없습니다."),

    // FAQ
    FAQ_NOT_FOUND(404, "FAQ_NOT_FOUND", "FAQ를 찾을 수 없습니다."),
    FAQ_CATEGORY_NOT_FOUND(404, "FAQ_CATEGORY_NOT_FOUND", "FAQ 카테고리를 찾을 수 없습니다."),
    FAQ_CATEGORY_HAS_ITEMS(400, "FAQ_CATEGORY_HAS_ITEMS", "소속된 FAQ가 있어 카테고리를 삭제할 수 없습니다."),

    // 버그 제보
    BUG_REPORT_NOT_FOUND(404, "BUG_REPORT_NOT_FOUND", "버그 제보를 찾을 수 없습니다."),
    BUG_REPORT_INVALID_STATUS(400, "BUG_REPORT_INVALID_STATUS", "현재 상태에서는 해당 처리를 할 수 없습니다."),
    BUG_REPORT_STATUS_UNKNOWN(400, "BUG_REPORT_STATUS_UNKNOWN", "알 수 없는 버그 제보 상태입니다."),
    BUG_REPORT_CATEGORY_UNKNOWN(400, "BUG_REPORT_CATEGORY_UNKNOWN", "알 수 없는 버그 제보 분류입니다."),
    BUG_REPORT_PRIORITY_UNKNOWN(400, "BUG_REPORT_PRIORITY_UNKNOWN", "알 수 없는 버그 제보 우선순위입니다."),
    BUG_REPORT_PLATFORM_UNKNOWN(400, "BUG_REPORT_PLATFORM_UNKNOWN", "알 수 없는 버그 제보 플랫폼입니다."),

    // 배너
    BANNER_NOT_FOUND(404, "BANNER_NOT_FOUND", "배너를 찾을 수 없습니다."),

    // 랭크
    RANK_TYPE_UNKNOWN(400, "RANK_TYPE_UNKNOWN", "알 수 없는 랭크 타입입니다."),
    RANK_PERIOD_NOT_FOUND(404, "RANK_PERIOD_NOT_FOUND", "랭킹 기간을 찾을 수 없습니다."),
    RANK_PRIZE_NOT_FOUND(404, "RANK_PRIZE_NOT_FOUND", "랭킹 경품을 찾을 수 없습니다."),

    // 배너
    BANNER_TYPE_UNKNOWN(400, "BANNER_TYPE_UNKNOWN", "알 수 없는 배너 유형입니다."),

    // 이벤트
    EVENT_STATUS_UNKNOWN(400, "EVENT_STATUS_UNKNOWN", "알 수 없는 이벤트 상태입니다."),
    EVENT_NOT_FOUND(404, "EVENT_NOT_FOUND", "이벤트를 찾을 수 없습니다."),
    EVENT_ANNOUNCEMENT_NOT_FOUND(404, "EVENT_ANNOUNCEMENT_NOT_FOUND", "당첨자 발표 공지를 찾을 수 없습니다."),
    EVENT_ANNOUNCEMENT_ALREADY_EXISTS(409, "EVENT_ANNOUNCEMENT_ALREADY_EXISTS", "이미 당첨자 발표 공지가 등록된 이벤트입니다."),
    EVENT_WINNER_NOT_FOUND(404, "EVENT_WINNER_NOT_FOUND", "당첨자를 찾을 수 없습니다."),

    // 가게
    FOOD_TYPE_UNKNOWN(400, "FOOD_TYPE_UNKNOWN", "알 수 없는 음식 종류입니다."),
    AMENITY_UNKNOWN(400, "AMENITY_UNKNOWN", "알 수 없는 편의시설입니다."),

    // 추천인
    REFERRAL_NOT_FOUND(404, "REFERRAL_NOT_FOUND", "추천 이력을 찾을 수 없습니다."),
    REFERRAL_REFERRER_NOT_FOUND(400, "REFERRAL_REFERRER_NOT_FOUND", "존재하지 않는 추천인 닉네임입니다."),
    REFERRAL_SELF_NOT_ALLOWED(400, "REFERRAL_SELF_NOT_ALLOWED", "자기 자신을 추천인으로 설정할 수 없습니다."),
    REFERRAL_ALREADY_EXISTS(400, "REFERRAL_ALREADY_EXISTS", "이미 추천인이 등록되어 있습니다."),
    REFERRAL_INVALID_STATUS(400, "REFERRAL_INVALID_STATUS", "처리할 수 없는 추천 상태입니다."),

    // 팔로우
    FOLLOW_SELF_NOT_ALLOWED(400, "FOLLOW_SELF_NOT_ALLOWED", "자기 자신을 팔로우할 수 없습니다."),
    FOLLOW_ALREADY_EXISTS(400, "FOLLOW_ALREADY_EXISTS", "이미 팔로우한 사용자입니다."),
    FOLLOW_NOT_FOUND(400, "FOLLOW_NOT_FOUND", "팔로우 관계가 존재하지 않습니다."),
    FOLLOW_TARGET_NOT_FOUND(404, "FOLLOW_TARGET_NOT_FOUND", "팔로우 대상 회원을 찾을 수 없습니다."),
    FOLLOWER_REMOVE_ACCESS_DENIED(403, "FOLLOWER_REMOVE_ACCESS_DENIED", "본인의 팔로워만 삭제할 수 있습니다."),

    // 회원 enum
    GENDER_TYPE_UNKNOWN(400, "GENDER_TYPE_UNKNOWN", "알 수 없는 성별입니다."),
    SOCIAL_PROVIDER_TYPE_UNKNOWN(400, "SOCIAL_PROVIDER_TYPE_UNKNOWN", "알 수 없는 소셜 로그인 제공자입니다."),
    WITHDRAWAL_REASON_TYPE_UNKNOWN(400, "WITHDRAWAL_REASON_TYPE_UNKNOWN", "알 수 없는 탈퇴 사유입니다."),
    MEMBER_STATUS_TYPE_UNKNOWN(400, "MEMBER_STATUS_TYPE_UNKNOWN", "알 수 없는 회원 상태입니다."),
    MEMBER_GRADE_TYPE_UNKNOWN(400, "MEMBER_GRADE_TYPE_UNKNOWN", "알 수 없는 회원 등급입니다."),

    // 소셜 로그인
    SOCIAL_ACCOUNT_ALREADY_REGISTERED(409, "SOCIAL_ACCOUNT_ALREADY_REGISTERED", "이미 가입된 소셜 계정입니다."),
    SOCIAL_EMAIL_REQUIRED(400, "SOCIAL_EMAIL_REQUIRED", "카카오 이메일 제공 동의가 필요합니다."),
    SOCIAL_OAUTH_FAILED(502, "SOCIAL_OAUTH_FAILED", "소셜 로그인 처리 중 오류가 발생했습니다."),
    KAKAO_TEMP_TOKEN_EXPIRED(400, "KAKAO_TEMP_TOKEN_EXPIRED", "카카오 인증이 만료되었습니다. 다시 시도해주세요."),
    NAVER_TEMP_TOKEN_EXPIRED(400, "NAVER_TEMP_TOKEN_EXPIRED", "네이버 인증이 만료되었습니다. 다시 시도해주세요."),
    FACEBOOK_TEMP_TOKEN_EXPIRED(400, "FACEBOOK_TEMP_TOKEN_EXPIRED", "페이스북 인증이 만료되었습니다. 다시 시도해주세요."),
    APPLE_TEMP_TOKEN_EXPIRED(400, "APPLE_TEMP_TOKEN_EXPIRED", "애플 인증이 만료되었습니다. 다시 시도해주세요."),
    APPLE_ID_TOKEN_INVALID(400, "APPLE_ID_TOKEN_INVALID", "애플 인증 토큰이 유효하지 않습니다."),

    // 검색
    SEARCH_KEYWORD_BLANK(400, "SEARCH_KEYWORD_BLANK", "검색어를 입력해주세요."),

    // Rate Limiting
    RATE_LIMIT_EXCEEDED(429, "RATE_LIMIT_EXCEEDED", "요청 횟수가 초과되었습니다. 잠시 후 다시 시도해주세요."),

    // 예약
    RESERVATION_NOT_FOUND(404, "RESERVATION_NOT_FOUND", "예약을 찾을 수 없습니다."),
    RESERVATION_ACCESS_DENIED(403, "RESERVATION_ACCESS_DENIED", "본인의 예약만 처리할 수 있습니다."),
    RESERVATION_INVALID_STATUS(400, "RESERVATION_INVALID_STATUS", "현재 상태에서는 해당 처리를 할 수 없습니다."),
    RESERVATION_ALREADY_CANCELED(409, "RESERVATION_ALREADY_CANCELED", "이미 취소된 예약입니다."),
    RESERVATION_ALREADY_REJECTED(409, "RESERVATION_ALREADY_REJECTED", "점주가 거절한 예약은 취소할 수 없습니다."),
    RESERVATION_ALREADY_COMPLETED(409, "RESERVATION_ALREADY_COMPLETED", "이미 방문 완료된 예약은 취소할 수 없습니다."),
    RESERVATION_SLOT_FULL(409, "RESERVATION_SLOT_FULL", "해당 시간대는 예약이 마감되었습니다."),
    RESERVATION_INVALID_TIME(400, "RESERVATION_INVALID_TIME", "예약할 수 없는 시간입니다."),
    RESERVATION_PAST_NOT_ALLOWED(400, "RESERVATION_PAST_NOT_ALLOWED", "지난 일시는 예약할 수 없습니다."),
    RESERVATION_TERMS_NOT_AGREED(400, "RESERVATION_TERMS_NOT_AGREED", "필수 약관에 동의해야 예약할 수 있습니다."),
    DUPLICATE_RESERVATION(409, "DUPLICATE_RESERVATION", "이미 해당 날짜에 예약이 존재합니다. 예약을 변경하려면 기존 예약을 취소해주세요."),

    // 제휴 신청
    PARTNERSHIP_REQUEST_NOT_FOUND(404, "PARTNERSHIP_REQUEST_NOT_FOUND", "제휴 신청을 찾을 수 없습니다."),
    PARTNERSHIP_STATUS_UNKNOWN(400, "PARTNERSHIP_STATUS_UNKNOWN", "알 수 없는 제휴 신청 상태입니다.");

    private final int httpStatusCode;
    private final String code;
    private final String defaultMessage;
}
