plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    implementation project(':web-application')

    implementation 'org.springframework.boot:spring-boot-starter-mail'

    testImplementation 'com.tngtech.archunit:archunit-junit5:1.2.1'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
