package com.tastyhouse.domain.exception;

public enum DomainErrorCode implements ErrorCodeSpec {

    ORDER_ACCESS_DENIED(403, "ORDER_ACCESS_DENIED", "본인의 주문만 조회할 수 있습니다."),
    ORDER_MINIMUM_AMOUNT_NOT_MET(400, "ORDER_MINIMUM_AMOUNT_NOT_MET", "최소 주문 금액을 충족하지 않습니다."),
    ORDER_METHOD_UNKNOWN(400, "ORDER_METHOD_UNKNOWN", "알 수 없는 주문 방법입니다."),
    ORDER_STATUS_UNKNOWN(400, "ORDER_STATUS_UNKNOWN", "알 수 없는 주문 상태입니다."),
    ORDER_INVALID_STATUS_TRANSITION(400, "ORDER_INVALID_STATUS_TRANSITION", "현재 주문 상태에서는 해당 상태로 변경할 수 없습니다."),
    ORDER_ALREADY_CANCELLED(409, "ORDER_ALREADY_CANCELLED", "이미 취소된 주문입니다."),
    ORDER_ALREADY_COMPLETED(409, "ORDER_ALREADY_COMPLETED", "이미 완료된 주문은 변경할 수 없습니다."),
    ORDER_ALREADY_PREPARING(409, "ORDER_ALREADY_PREPARING", "조리가 시작된 주문은 변경할 수 없습니다."),
    ORDER_AMOUNT_NEGATIVE(400, "ORDER_AMOUNT_NEGATIVE", "주문 금액은 음수일 수 없습니다."),
    ORDER_AMOUNT_NOT_CONSISTENT(400, "ORDER_AMOUNT_NOT_CONSISTENT", "주문 금액 합계가 일치하지 않습니다."),

    COUPON_NOT_AVAILABLE(400, "COUPON_NOT_AVAILABLE", "사용할 수 없는 쿠폰입니다."),
    COUPON_DISCOUNT_TYPE_UNKNOWN(400, "COUPON_DISCOUNT_TYPE_UNKNOWN", "알 수 없는 할인 유형입니다."),
    COUPON_DISCOUNT_AMOUNT_INVALID(400, "COUPON_DISCOUNT_AMOUNT_INVALID", "할인 금액은 1 이상이어야 합니다."),
    COUPON_DISCOUNT_RATE_INVALID(400, "COUPON_DISCOUNT_RATE_INVALID", "할인율은 1 이상 100 이하여야 합니다."),
    COUPON_AMOUNT_NEGATIVE(400, "COUPON_AMOUNT_NEGATIVE", "쿠폰 금액은 음수일 수 없습니다."),
    COUPON_PERIOD_INVALID(400, "COUPON_PERIOD_INVALID", "쿠폰 기간의 시작 일시는 종료 일시보다 늦을 수 없습니다."),
    COUPON_USE_END_AT_REQUIRED(400, "COUPON_USE_END_AT_REQUIRED", "쿠폰 사용 종료 일시는 필수입니다."),

    PAYMENT_NOT_PENDING(400, "PAYMENT_NOT_PENDING", "대기 중인 결제만 완료 처리할 수 있습니다."),
    PAYMENT_METHOD_UNKNOWN(400, "PAYMENT_METHOD_UNKNOWN", "알 수 없는 결제 방법입니다."),
    PG_PROVIDER_UNKNOWN(400, "PG_PROVIDER_UNKNOWN", "알 수 없는 PG사입니다."),

    ALREADY_WITHDRAWN(409, "ALREADY_WITHDRAWN", "이미 탈퇴한 회원입니다."),
    MEMBER_ALREADY_SUSPENDED(409, "MEMBER_ALREADY_SUSPENDED", "이미 정지된 회원입니다."),
    MEMBER_ALREADY_ACTIVE(409, "MEMBER_ALREADY_ACTIVE", "이미 활성 상태인 회원입니다."),
    MEMBER_STATUS_CHANGE_NOT_ALLOWED(400, "MEMBER_STATUS_CHANGE_NOT_ALLOWED", "탈퇴한 회원은 상태를 변경할 수 없습니다."),

    ADMIN_ROLE_UNKNOWN(400, "ADMIN_ROLE_UNKNOWN", "알 수 없는 관리자 권한입니다."),

    CEO_LOGIN_RESULT_UNKNOWN(400, "CEO_LOGIN_RESULT_UNKNOWN", "알 수 없는 로그인 결과입니다."),

    SMS_VERIFICATION_CODE_EXPIRED(400, "VERIFICATION_CODE_EXPIRED", "인증번호가 만료되었습니다. 인증번호를 다시 요청해주세요."),
    SMS_VERIFICATION_CODE_MISMATCH(400, "VERIFICATION_CODE_MISMATCH", "인증번호가 일치하지 않습니다."),

    MAIL_VERIFICATION_CODE_EXPIRED(400, "EMAIL_VERIFICATION_CODE_EXPIRED", "인증번호가 만료되었습니다. 인증번호를 다시 요청해주세요."),
    MAIL_VERIFICATION_CODE_MISMATCH(400, "EMAIL_VERIFICATION_CODE_MISMATCH", "인증번호가 일치하지 않습니다."),

    POINT_INSUFFICIENT(400, "POINT_INSUFFICIENT", "포인트가 부족합니다."),
    POINT_TYPE_UNKNOWN(400, "POINT_TYPE_UNKNOWN", "알 수 없는 포인트 유형입니다."),

    REVIEW_SORT_TYPE_UNKNOWN(400, "REVIEW_SORT_TYPE_UNKNOWN", "알 수 없는 리뷰 정렬 방식입니다."),
    NOTIFICATION_TYPE_UNKNOWN(400, "NOTIFICATION_TYPE_UNKNOWN", "알 수 없는 알림 유형입니다."),
    REVIEW_BLIND_REQUEST_NOT_PENDING(409, "REVIEW_BLIND_REQUEST_NOT_PENDING", "대기 중인 요청만 처리할 수 있습니다."),
    REVIEW_BLIND_REASON_UNKNOWN(400, "REVIEW_BLIND_REASON_UNKNOWN", "알 수 없는 게시중단 요청 사유입니다."),
    REVIEW_BLIND_REQUEST_NOT_APPROVED(409, "REVIEW_BLIND_REQUEST_NOT_APPROVED", "게시중단 상태의 리뷰가 아닙니다."),
    REVIEW_BLIND_STATUS_UNKNOWN(400, "REVIEW_BLIND_STATUS_UNKNOWN", "알 수 없는 게시중단 처리 상태입니다."),
    REVIEW_TAB_UNKNOWN(400, "REVIEW_TAB_UNKNOWN", "알 수 없는 리뷰 목록 탭입니다."),

    MENU_REVIEW_NOT_ALLOWED(400, "MENU_REVIEW_NOT_ALLOWED", "평가할 수 없는 메뉴입니다."),

    DAY_TYPE_UNKNOWN(400, "DAY_TYPE_UNKNOWN", "알 수 없는 요일 유형입니다."),
    CLOSED_DAY_TYPE_UNKNOWN(400, "CLOSED_DAY_TYPE_UNKNOWN", "알 수 없는 정기 휴무 유형입니다."),

    SHOP_CUP_DEPOSIT_NOT_ENABLED(400, "SHOP_CUP_DEPOSIT_NOT_ENABLED", "일회용컵 보증금제 대상 가게가 아닙니다."),
    SHOP_BUSINESS_HOUR_INVALID_UNIT(400, "SHOP_BUSINESS_HOUR_INVALID_UNIT", "영업시간은 5분 단위로 설정해야 합니다."),
    SHOP_BUSINESS_HOUR_INVALID_RANGE(400, "SHOP_BUSINESS_HOUR_INVALID_RANGE", "영업시간은 최소 1시간, 최대 23시간 55분이어야 합니다."),
    SHOP_TEMPORARY_CLOSURE_INVALID_PERIOD(400, "SHOP_TEMPORARY_CLOSURE_INVALID_PERIOD", "임시 휴무 종료일은 시작일과 같거나 이후여야 합니다."),
    SHOP_VIRTUAL_NUMBER_INVALID(400, "SHOP_VIRTUAL_NUMBER_INVALID", "가상번호 발급 조건(지정 국번, 8~13자리)을 충족하지 않습니다."),
    SHOP_ALREADY_PERMANENTLY_CLOSED(400, "SHOP_ALREADY_PERMANENTLY_CLOSED", "폐업한 가게는 정보를 수정하거나 다시 노출할 수 없습니다."),
    SHOP_MIN_ORDER_AMOUNT_OUT_OF_RANGE(400, "SHOP_MIN_ORDER_AMOUNT_OUT_OF_RANGE", "최소주문금액은 5,000원 이상 30,000원 이하여야 합니다."),

    SHOP_MINIMUM_ORDER_AMOUNT_NOT_MET(400, "SHOP_MINIMUM_ORDER_AMOUNT_NOT_MET", "가게 최소주문금액을 충족하지 않습니다."),
    SHOP_DIRECTIONS_GUIDE_TOO_LONG(400, "SHOP_DIRECTIONS_GUIDE_TOO_LONG", "찾아오는 길 안내는 최대 200자까지 입력할 수 있습니다."),
    SHOP_ORIGIN_SOURCE_TYPE_UNKNOWN(400, "SHOP_ORIGIN_SOURCE_TYPE_UNKNOWN", "원산지 입력 방식이 올바르지 않습니다."),
    SHOP_ORIGIN_CONTENT_REQUIRED(400, "SHOP_ORIGIN_CONTENT_REQUIRED", "원산지 정보를 입력해 주세요."),
    SHOP_ORIGIN_CONTENT_TOO_LONG(400, "SHOP_ORIGIN_CONTENT_TOO_LONG", "원산지 정보는 최대 2000자까지 입력할 수 있습니다."),
    SHOP_ORIGIN_URL_REQUIRED(400, "SHOP_ORIGIN_URL_REQUIRED", "본사 제공 URL을 입력해 주세요."),
    SHOP_ORIGIN_URL_TOO_LONG(400, "SHOP_ORIGIN_URL_TOO_LONG", "본사 제공 URL은 최대 500자까지 입력할 수 있습니다."),
    SHOP_ORIGIN_URL_INVALID(400, "SHOP_ORIGIN_URL_INVALID", "올바른 URL 형식이 아닙니다."),
    SHOP_RIDER_VISIT_GUIDE_TOO_LONG(400, "SHOP_RIDER_VISIT_GUIDE_TOO_LONG", "라이더 가게방문 안내는 최대 200자까지 입력할 수 있습니다."),
    SHOP_RIDER_PICKUP_DETAIL_ADDRESS_TOO_LONG(400, "SHOP_RIDER_PICKUP_DETAIL_ADDRESS_TOO_LONG", "픽업 상세주소는 최대 100자까지 입력할 수 있습니다."),
    SHOP_RIDER_PICKUP_LOCATION_INCOMPLETE(400, "SHOP_RIDER_PICKUP_LOCATION_INCOMPLETE", "픽업 위치는 주소와 좌표를 모두 입력해야 합니다."),
    SHOP_RIDER_PICKUP_LOCATION_INVALID(400, "SHOP_RIDER_PICKUP_LOCATION_INVALID", "픽업 위치 좌표가 올바르지 않습니다."),
    SHOP_RIDER_GUIDE_ACTION_TYPE_UNKNOWN(400, "SHOP_RIDER_GUIDE_ACTION_TYPE_UNKNOWN", "알 수 없는 라이더 안내 조치 유형입니다."),
    SHOP_IMAGE_CHANGE_REQUEST_NOT_PENDING(409, "SHOP_IMAGE_CHANGE_REQUEST_NOT_PENDING", "대기 상태가 아닌 요청은 처리할 수 없습니다."),
    SHOP_IMAGE_SPEC_INVALID(400, "SHOP_IMAGE_SPEC_INVALID", "이미지 규격(형식/용량/해상도/비율)을 충족하지 않습니다."),
    SHOP_IMAGE_TYPE_UNKNOWN(400, "SHOP_IMAGE_TYPE_UNKNOWN", "알 수 없는 이미지 유형입니다."),
    SHOP_SUSPENSION_INVALID_PERIOD(400, "SHOP_SUSPENSION_INVALID_PERIOD", "임시중지 종료시간은 시작시간 이후여야 합니다."),
    SHOP_SUSPENSION_REASON_UNKNOWN(400, "SHOP_SUSPENSION_REASON_UNKNOWN", "알 수 없는 임시중지 사유입니다."),
    SHOP_CONTENT_TYPE_UNKNOWN(400, "SHOP_CONTENT_TYPE_UNKNOWN", "알 수 없는 콘텐츠 형태입니다."),
    SHOP_CONTENT_TOPIC_UNKNOWN(400, "SHOP_CONTENT_TOPIC_UNKNOWN", "알 수 없는 콘텐츠 주제입니다."),
    SHOP_CONTENT_DESCRIPTION_TOO_LONG(400, "SHOP_CONTENT_DESCRIPTION_TOO_LONG", "콘텐츠 설명글은 최대 50자까지 입력할 수 있습니다."),
    SHOP_CONTENT_YOUTUBE_URL_INVALID(400, "SHOP_CONTENT_YOUTUBE_URL_INVALID", "유효한 유튜브 링크가 아닙니다."),

    HYGIENE_BADGE_TYPE_UNKNOWN(400, "HYGIENE_BADGE_TYPE_UNKNOWN", "알 수 없는 위생 인증 유형입니다."),

    SHOP_MENU_COLLECTION_IMAGE_NOT_PENDING(409, "SHOP_MENU_COLLECTION_IMAGE_NOT_PENDING", "대기 상태가 아닌 메뉴모음컷은 처리할 수 없습니다."),

    SHOP_DELIVERY_TIP_TIER_LIMIT_EXCEEDED(400, "SHOP_DELIVERY_TIP_TIER_LIMIT_EXCEEDED", "기본 배달팁 구간은 최대 3개까지 설정할 수 있습니다."),
    SHOP_DELIVERY_TIP_AMOUNT_OUT_OF_RANGE(400, "SHOP_DELIVERY_TIP_AMOUNT_OUT_OF_RANGE", "배달팁은 0원 이상 5,000원 미만이어야 합니다."),
    SHOP_DELIVERY_TIP_EXTRA_AMOUNT_OUT_OF_RANGE(400, "SHOP_DELIVERY_TIP_EXTRA_AMOUNT_OUT_OF_RANGE", "추가 배달팁은 10,000원 이하여야 합니다."),
    SHOP_DELIVERY_TIP_DISTANCE_BASE_INVALID(400, "SHOP_DELIVERY_TIP_DISTANCE_BASE_INVALID", "기본배달거리는 1, 1.5, 2, 2.5, 3km 중에서 선택해야 합니다."),
    SHOP_DELIVERY_TIP_DISTANCE_SURCHARGE_OUT_OF_RANGE(400, "SHOP_DELIVERY_TIP_DISTANCE_SURCHARGE_OUT_OF_RANGE", "거리 할증 금액이 허용 범위를 벗어났습니다."),
    SHOP_DELIVERY_TIP_SCHEDULE_OVERLAP(400, "SHOP_DELIVERY_TIP_SCHEDULE_OVERLAP", "같은 요일의 시간대가 서로 겹칠 수 없습니다."),
    SHOP_DELIVERY_TIP_SCHEDULE_DAY_TYPE_NOT_ALLOWED(400, "SHOP_DELIVERY_TIP_SCHEDULE_DAY_TYPE_NOT_ALLOWED", "공휴일은 공휴일 배달팁으로 설정해야 합니다."),
    DELIVERY_TIP_EXTRA_TYPE_UNKNOWN(400, "DELIVERY_TIP_EXTRA_TYPE_UNKNOWN", "알 수 없는 추가 배달팁 유형입니다."),
    DELIVERY_TIP_DISTANCE_UNIT_UNKNOWN(400, "DELIVERY_TIP_DISTANCE_UNIT_UNKNOWN", "알 수 없는 거리 할증 단위입니다."),

    SHOP_DELIVERY_AREA_RADIUS_EXCEEDED(400, "SHOP_DELIVERY_AREA_RADIUS_EXCEEDED", "배달지역은 가게 주소 기준 7km를 넘을 수 없습니다."),
    SHOP_DELIVERY_AREA_POLYGON_INVALID(400, "SHOP_DELIVERY_AREA_POLYGON_INVALID", "배달지역 도형이 올바르지 않습니다."),
    SHOP_DELIVERY_AREA_COUNT_EXCEEDED(400, "SHOP_DELIVERY_AREA_COUNT_EXCEEDED", "배달가능지역은 최대 500개까지 등록할 수 있습니다."),

    SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_NOT_PENDING(409, "SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_NOT_PENDING", "접수 대기 상태가 아닌 신청은 처리할 수 없습니다."),
    SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_NOT_IN_PROGRESS(409, "SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_NOT_IN_PROGRESS", "조정 중 상태가 아닌 신청은 완료할 수 없습니다."),
    SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_ALREADY_CLOSED(409, "SHOP_DELIVERY_AREA_ADJUSTMENT_REQUEST_ALREADY_CLOSED", "이미 종결된 신청입니다."),
    DELIVERY_AREA_ADJUSTMENT_STATUS_UNKNOWN(400, "DELIVERY_AREA_ADJUSTMENT_STATUS_UNKNOWN", "알 수 없는 배달지역 조정 신청 상태입니다."),

    SHOP_REQUEST_TYPE_UNKNOWN(400, "SHOP_REQUEST_TYPE_UNKNOWN", "알 수 없는 요청 유형입니다."),
    SHOP_STORE_PRICE_VERIFICATION_NOT_PENDING(400, "SHOP_STORE_PRICE_VERIFICATION_NOT_PENDING", "검수 대기·진행 중인 요청만 처리할 수 있습니다."),
    SHOP_STORE_PRICE_VERIFICATION_STATUS_UNKNOWN(400, "SHOP_STORE_PRICE_VERIFICATION_STATUS_UNKNOWN", "알 수 없는 매장 가격 인증 상태입니다."),
    SHOP_REQUEST_STATUS_UNKNOWN(400, "SHOP_REQUEST_STATUS_UNKNOWN", "알 수 없는 요청 상태입니다."),
    SHOP_REQUEST_NOT_CANCELABLE(409, "SHOP_REQUEST_NOT_CANCELABLE", "대기중인 요청만 취소할 수 있습니다."),

    SHOP_CHANGE_CATEGORY_UNKNOWN(400, "SHOP_CHANGE_CATEGORY_UNKNOWN", "알 수 없는 변경 분류입니다."),
    SHOP_CHANGE_TYPE_UNKNOWN(400, "SHOP_CHANGE_TYPE_UNKNOWN", "알 수 없는 변경 유형입니다."),

    SHOP_CEO_ASSIGNMENT_ACTION_UNKNOWN(400, "SHOP_CEO_ASSIGNMENT_ACTION_UNKNOWN", "알 수 없는 접근권한 조치 유형입니다."),

    POLICY_TYPE_UNKNOWN(400, "POLICY_TYPE_UNKNOWN", "알 수 없는 정책 타입입니다."),

    PRODUCT_PRICE_NEGATIVE(400, "PRODUCT_PRICE_NEGATIVE", "상품 가격은 음수일 수 없습니다."),
    PRODUCT_PRICE_NAME_REQUIRED(400, "PRODUCT_PRICE_NAME_REQUIRED", "가격이 2개 이상이면 가격명을 입력해야 합니다."),
    PRODUCT_DISCOUNT_PRICE_EXCEEDS_ORIGINAL(400, "PRODUCT_DISCOUNT_PRICE_EXCEEDS_ORIGINAL", "할인가는 정가보다 클 수 없습니다."),
    PRODUCT_NOT_SOLD_OUT(400, "PRODUCT_NOT_SOLD_OUT", "품절 상태가 아닌 메뉴는 기간을 변경할 수 없습니다."),
    PRODUCT_OPTION_MIN_SELECT_VIOLATION(400, "PRODUCT_OPTION_MIN_SELECT_VIOLATION", "최소 선택 개수만큼의 옵션은 판매 중이어야 합니다."),
    PRODUCT_RELEASE_TARGET_UNKNOWN(400, "PRODUCT_RELEASE_TARGET_UNKNOWN", "해제 대상이 올바르지 않습니다."),
    PRODUCT_OPTION_TYPE_UNKNOWN(400, "PRODUCT_OPTION_TYPE_UNKNOWN", "옵션 종류가 올바르지 않습니다."),
    PRODUCT_ALREADY_DELETED(400, "PRODUCT_ALREADY_DELETED", "이미 삭제된 메뉴입니다."),
    PRODUCT_OPTION_GROUP_REQUIRES_ZERO_PRICE_OPTION(400, "PRODUCT_OPTION_GROUP_REQUIRES_ZERO_PRICE_OPTION", "필수 옵션그룹에는 0원 옵션이 1개 이상 있어야 합니다."),
    PRODUCT_OPTION_MAX_SELECT_VIOLATION(400, "PRODUCT_OPTION_MAX_SELECT_VIOLATION", "옵션그룹의 최대 선택 개수보다 적게 남길 수 없습니다."),
    PRODUCT_OPTION_GROUP_MERGE_ENTRY_TYPE_UNKNOWN(400, "PRODUCT_OPTION_GROUP_MERGE_ENTRY_TYPE_UNKNOWN", "합치기 진입 경로가 올바르지 않습니다."),
    PRODUCT_OPTION_GROUP_TYPE_UNKNOWN(400, "PRODUCT_OPTION_GROUP_TYPE_UNKNOWN", "옵션그룹 유형이 올바르지 않습니다."),
    PRODUCT_OPTION_GROUP_DEPOSIT_CANNOT_BE_REQUIRED(400, "PRODUCT_OPTION_GROUP_DEPOSIT_CANNOT_BE_REQUIRED", "일회용컵 보증금 옵션그룹은 필수 선택으로 설정할 수 없습니다."),
    PRODUCT_OPTION_GROUP_DEPOSIT_SELECT_FIXED(400, "PRODUCT_OPTION_GROUP_DEPOSIT_SELECT_FIXED", "일회용컵 보증금 옵션그룹의 선택 개수는 변경할 수 없습니다."),
    PRODUCT_OPTION_CUP_COUNT_REQUIRED(400, "PRODUCT_OPTION_CUP_COUNT_REQUIRED", "일회용컵 제공 개수는 필수입니다."),
    PRODUCT_OPTION_CUP_COUNT_INVALID(400, "PRODUCT_OPTION_CUP_COUNT_INVALID", "일회용컵 제공 개수는 1개 이상 10개 이하여야 합니다."),
    PRODUCT_OPTION_CUP_COUNT_NOT_ALLOWED(400, "PRODUCT_OPTION_CUP_COUNT_NOT_ALLOWED", "일반 옵션에는 일회용컵 제공 개수를 설정할 수 없습니다."),
    PRODUCT_OPTION_DEPOSIT_ADDITIONAL_PRICE_NOT_ALLOWED(400, "PRODUCT_OPTION_DEPOSIT_ADDITIONAL_PRICE_NOT_ALLOWED", "일회용컵 보증금 옵션에는 추가 금액을 설정할 수 없습니다."),
    PRODUCT_OPTION_PERSONAL_CUP_NOT_IN_DEPOSIT_GROUP(400, "PRODUCT_OPTION_PERSONAL_CUP_NOT_IN_DEPOSIT_GROUP", "개인컵 사용 옵션은 일회용컵 보증금 옵션그룹에만 등록할 수 있습니다."),
    PRODUCT_EXPOSURE_PERIOD_INVALID(400, "PRODUCT_EXPOSURE_PERIOD_INVALID", "노출 종료일은 시작일보다 빠를 수 없습니다."),
    PRODUCT_IMAGE_CHANGE_REQUEST_NOT_PENDING(400, "PRODUCT_IMAGE_CHANGE_REQUEST_NOT_PENDING", "검수 대기 상태가 아닙니다."),
    PRODUCT_VEGETARIAN_TYPE_UNKNOWN(400, "PRODUCT_VEGETARIAN_TYPE_UNKNOWN", "채식 단계가 올바르지 않습니다."),
    PRODUCT_VEGETARIAN_REQUEST_NOT_PENDING(400, "PRODUCT_VEGETARIAN_REQUEST_NOT_PENDING", "검수 대기 상태가 아닙니다."),
    PRODUCT_NUTRITION_REQUIRED_FIELD_MISSING(400, "PRODUCT_NUTRITION_REQUIRED_FIELD_MISSING", "열량·당류·단백질·포화지방·나트륨은 함께 입력해야 합니다."),
    PRODUCT_NUTRITION_VALUE_NEGATIVE(400, "PRODUCT_NUTRITION_VALUE_NEGATIVE", "영양성분 값은 음수일 수 없습니다."),
    PRODUCT_ALLERGEN_TYPE_UNKNOWN(400, "PRODUCT_ALLERGEN_TYPE_UNKNOWN", "알레르기 유발성분이 올바르지 않습니다."),
    PRODUCT_WEIGHT_TEXT_TOO_LONG(400, "PRODUCT_WEIGHT_TEXT_TOO_LONG", "중량 표기는 50자 이내로 입력해 주세요."),

    PRODUCT_REPRESENTATIVE_REQUEST_NOT_PENDING(400, "PRODUCT_REPRESENTATIVE_REQUEST_NOT_PENDING", "검수 대기 상태가 아닙니다."),

    PRODUCT_FEEDBACK_TYPE_UNKNOWN(400, "PRODUCT_FEEDBACK_TYPE_UNKNOWN", "의견 유형이 올바르지 않습니다."),
    PRODUCT_FEEDBACK_CONTENT_REQUIRED(400, "PRODUCT_FEEDBACK_CONTENT_REQUIRED", "기타 의견은 내용을 입력해 주세요."),
    PRODUCT_FEEDBACK_CONTENT_TOO_LONG(400, "PRODUCT_FEEDBACK_CONTENT_TOO_LONG", "의견은 500자 이내로 입력해 주세요."),

    BUG_REPORT_INVALID_STATUS(400, "BUG_REPORT_INVALID_STATUS", "현재 상태에서는 해당 처리를 할 수 없습니다."),
    BUG_REPORT_STATUS_UNKNOWN(400, "BUG_REPORT_STATUS_UNKNOWN", "알 수 없는 버그 제보 상태입니다."),
    BUG_REPORT_CATEGORY_UNKNOWN(400, "BUG_REPORT_CATEGORY_UNKNOWN", "알 수 없는 버그 제보 분류입니다."),
    BUG_REPORT_PRIORITY_UNKNOWN(400, "BUG_REPORT_PRIORITY_UNKNOWN", "알 수 없는 버그 제보 우선순위입니다."),
    BUG_REPORT_PLATFORM_UNKNOWN(400, "BUG_REPORT_PLATFORM_UNKNOWN", "알 수 없는 버그 제보 플랫폼입니다."),

    BANNER_TYPE_UNKNOWN(400, "BANNER_TYPE_UNKNOWN", "알 수 없는 배너 유형입니다."),

    RANK_TYPE_UNKNOWN(400, "RANK_TYPE_UNKNOWN", "알 수 없는 랭크 타입입니다."),

    EVENT_STATUS_UNKNOWN(400, "EVENT_STATUS_UNKNOWN", "알 수 없는 이벤트 상태입니다."),

    FOOD_TYPE_UNKNOWN(400, "FOOD_TYPE_UNKNOWN", "알 수 없는 음식 종류입니다."),
    AMENITY_UNKNOWN(400, "AMENITY_UNKNOWN", "알 수 없는 편의시설입니다."),

    REFERRAL_INVALID_STATUS(400, "REFERRAL_INVALID_STATUS", "처리할 수 없는 추천 상태입니다."),

    GENDER_TYPE_UNKNOWN(400, "GENDER_TYPE_UNKNOWN", "알 수 없는 성별입니다."),
    SOCIAL_PROVIDER_TYPE_UNKNOWN(400, "SOCIAL_PROVIDER_TYPE_UNKNOWN", "알 수 없는 소셜 로그인 제공자입니다."),
    WITHDRAWAL_REASON_TYPE_UNKNOWN(400, "WITHDRAWAL_REASON_TYPE_UNKNOWN", "알 수 없는 탈퇴 사유입니다."),
    MEMBER_STATUS_TYPE_UNKNOWN(400, "MEMBER_STATUS_TYPE_UNKNOWN", "알 수 없는 회원 상태입니다."),
    MEMBER_GRADE_TYPE_UNKNOWN(400, "MEMBER_GRADE_TYPE_UNKNOWN", "알 수 없는 회원 등급입니다."),

    RESERVATION_ACCESS_DENIED(403, "RESERVATION_ACCESS_DENIED", "본인의 예약만 처리할 수 있습니다."),
    RESERVATION_INVALID_STATUS(400, "RESERVATION_INVALID_STATUS", "현재 상태에서는 해당 처리를 할 수 없습니다."),
    RESERVATION_ALREADY_CANCELED(409, "RESERVATION_ALREADY_CANCELED", "이미 취소된 예약입니다."),
    RESERVATION_ALREADY_REJECTED(409, "RESERVATION_ALREADY_REJECTED", "점주가 거절한 예약은 취소할 수 없습니다."),
    RESERVATION_ALREADY_COMPLETED(409, "RESERVATION_ALREADY_COMPLETED", "이미 방문 완료된 예약은 취소할 수 없습니다."),
    RESERVATION_SLOT_FULL(409, "RESERVATION_SLOT_FULL", "해당 시간대는 예약이 마감되었습니다."),
    RESERVATION_PARTY_SIZE_INVALID(400, "RESERVATION_PARTY_SIZE_INVALID", "방문 인원수는 1명 이상이어야 합니다."),

    PARTNERSHIP_STATUS_UNKNOWN(400, "PARTNERSHIP_STATUS_UNKNOWN", "알 수 없는 제휴 신청 상태입니다.");

    private final int httpStatusCode;
    private final String code;
    private final String defaultMessage;

    DomainErrorCode(int httpStatusCode, String code, String defaultMessage) {
        this.httpStatusCode = httpStatusCode;
        this.code = code;
        this.defaultMessage = defaultMessage;
    }

    @Override
    public int getHttpStatusCode() {
        return this.httpStatusCode;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public String getDefaultMessage() {
        return this.defaultMessage;
    }
}
