plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    implementation project(':infrastructure:external')
    implementation project(':application')
    implementation project(':domain-module')

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
