plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    runtimeOnly project(':infrastructure:kakao-oauth')
    runtimeOnly project(':infrastructure:naver-oauth')
    runtimeOnly project(':infrastructure:apple-oauth')
    runtimeOnly project(':infrastructure:facebook-oauth')
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
