sms:
  provider: solapi # solapi | sns
  sender-number: ${SMS_SENDER_NUMBER}
  # SOLAPI
  solapi:
    api-key: ${SOLAPI_API_KEY}
    api-secret: ${SOLAPI_API_SECRET}
    sender-number: ${SMS_SENDER_NUMBER}
    base-url: https://api.solapi.com
    send-many-path: /messages/v4/send-many/detail
  # AWS
  aws:
    sns:
      access-key: ${AWS_SNS_ACCESS_KEY}
      secret-key: ${AWS_SNS_SECRET_KEY}
      region: ap-northeast-2
