plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    // Test
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.2.1'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
}

jar {
    enabled = true
    archiveClassifier = ''
}
