plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    implementation project(':domain-module')
    api project(':security-core')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-security'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
