dependencies {
    implementation project(':application')

    runtimeOnly project(':infrastructure:persistence')
    runtimeOnly project(':infrastructure:file-storage')
    runtimeOnly project(':infrastructure:crawling')
    runtimeOnly(project(':logging-module')) {
        exclude group: 'com.github.gavlyukovskiy', module: 'p6spy-spring-boot-starter'
    }

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.2.1'
    testImplementation(testFixtures(project(':application')))
}
