package com.tastyhouse.application.payment.store;

import com.tastyhouse.application.payment.port.out.write.TossPaymentRecordState;
import com.tastyhouse.domain.payment.model.TossPaymentRecord;
import com.tastyhouse.domain.payment.vo.PaymentId;

final class TossPaymentRecordStateMapper {
    private TossPaymentRecordStateMapper() {
    }

    static TossPaymentRecord toDomain(TossPaymentRecordState state) {
        return TossPaymentRecord.reconstitute(
            state.id(),
            state.paymentId() == null ? null : PaymentId.of(state.paymentId()),
            state.version(),
            state.paymentKey(),
            state.type(),
            state.orderId(),
            state.orderName(),
            state.mId(),
            state.currency(),
            state.method(),
            state.totalAmount(),
            state.balanceAmount(),
            state.status(),
            state.requestedAt(),
            state.approvedAt(),
            state.useEscrow(),
            state.lastTransactionKey(),
            state.suppliedAmount(),
            state.vat(),
            state.cultureExpense(),
            state.taxFreeAmount(),
            state.taxExemptionAmount(),
            state.partialCancelable(),
            state.cardAmount(),
            state.cardIssuerCode(),
            state.cardAcquirerCode(),
            state.cardNumber(),
            state.cardInstallmentPlanMonths(),
            state.cardApproveNo(),
            state.cardUseCardPoint(),
            state.cardType(),
            state.cardOwnerType(),
            state.cardAcquireStatus(),
            state.cardInterestFree(),
            state.cardInterestPayer(),
            state.virtualAccountType(),
            state.virtualAccountNumber(),
            state.virtualAccountBankCode(),
            state.virtualAccountCustomerName(),
            state.virtualAccountDueDate(),
            state.virtualAccountRefundStatus(),
            state.virtualAccountExpired(),
            state.virtualAccountSettlementStatus(),
            state.mobilePhoneCustomerMobilePhone(),
            state.mobilePhoneSettlementStatus(),
            state.mobilePhoneReceiptUrl(),
            state.transferBankCode(),
            state.transferSettlementStatus(),
            state.easyPayProvider(),
            state.easyPayAmount(),
            state.easyPayDiscountAmount(),
            state.receiptUrl(),
            state.checkoutUrl(),
            state.failureCode(),
            state.failureMessage(),
            state.country(),
            state.createdAt()
        );
    }

    static TossPaymentRecordState toState(TossPaymentRecord tossPaymentRecord) {
        return new TossPaymentRecordState(
            tossPaymentRecord.getId(),
            tossPaymentRecord.getPaymentId() == null ? null : tossPaymentRecord.getPaymentId().value(),
            tossPaymentRecord.getVersion(),
            tossPaymentRecord.getPaymentKey(),
            tossPaymentRecord.getType(),
            tossPaymentRecord.getOrderId(),
            tossPaymentRecord.getOrderName(),
            tossPaymentRecord.getMId(),
            tossPaymentRecord.getCurrency(),
            tossPaymentRecord.getMethod(),
            tossPaymentRecord.getTotalAmount(),
            tossPaymentRecord.getBalanceAmount(),
            tossPaymentRecord.getStatus(),
            tossPaymentRecord.getRequestedAt(),
            tossPaymentRecord.getApprovedAt(),
            tossPaymentRecord.isUseEscrow(),
            tossPaymentRecord.getLastTransactionKey(),
            tossPaymentRecord.getSuppliedAmount(),
            tossPaymentRecord.getVat(),
            tossPaymentRecord.isCultureExpense(),
            tossPaymentRecord.getTaxFreeAmount(),
            tossPaymentRecord.getTaxExemptionAmount(),
            tossPaymentRecord.isPartialCancelable(),
            tossPaymentRecord.getCardAmount(),
            tossPaymentRecord.getCardIssuerCode(),
            tossPaymentRecord.getCardAcquirerCode(),
            tossPaymentRecord.getCardNumber(),
            tossPaymentRecord.getCardInstallmentPlanMonths(),
            tossPaymentRecord.getCardApproveNo(),
            tossPaymentRecord.isCardUseCardPoint(),
            tossPaymentRecord.getCardType(),
            tossPaymentRecord.getCardOwnerType(),
            tossPaymentRecord.getCardAcquireStatus(),
            tossPaymentRecord.isCardInterestFree(),
            tossPaymentRecord.getCardInterestPayer(),
            tossPaymentRecord.getVirtualAccountType(),
            tossPaymentRecord.getVirtualAccountNumber(),
            tossPaymentRecord.getVirtualAccountBankCode(),
            tossPaymentRecord.getVirtualAccountCustomerName(),
            tossPaymentRecord.getVirtualAccountDueDate(),
            tossPaymentRecord.getVirtualAccountRefundStatus(),
            tossPaymentRecord.isVirtualAccountExpired(),
            tossPaymentRecord.getVirtualAccountSettlementStatus(),
            tossPaymentRecord.getMobilePhoneCustomerMobilePhone(),
            tossPaymentRecord.getMobilePhoneSettlementStatus(),
            tossPaymentRecord.getMobilePhoneReceiptUrl(),
            tossPaymentRecord.getTransferBankCode(),
            tossPaymentRecord.getTransferSettlementStatus(),
            tossPaymentRecord.getEasyPayProvider(),
            tossPaymentRecord.getEasyPayAmount(),
            tossPaymentRecord.getEasyPayDiscountAmount(),
            tossPaymentRecord.getReceiptUrl(),
            tossPaymentRecord.getCheckoutUrl(),
            tossPaymentRecord.getFailureCode(),
            tossPaymentRecord.getFailureMessage(),
            tossPaymentRecord.getCountry(),
            tossPaymentRecord.getCreatedAt()
        );
    }
}
