plugins {
    id 'java-library'
    id 'idea'
}

dependencies {
    api project(':application')

    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    implementation project(':security-core')
    implementation 'org.springframework.security:spring-security-core'

    implementation 'org.springframework.boot:spring-boot-starter-aop'

    api "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.2.1'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}
